'use strict';
/* ============================================================
   DATA — banca de întrebări, nume de boți, nume de bresle
   Format întrebare: [categorie, dificultate 1-10, întrebare, corect, greșit, greșit, greșit]
   ============================================================ */
const TRIVIA_RAW = [
  // ---- Știință ----
  ['Știință', 1, 'Care este formula chimică a apei?', 'H2O', 'CO2', 'O2', 'HO'],
  ['Știință', 1, 'Câte picioare are o insectă?', '6', '8', '4', '10'],
  ['Știință', 1, 'Ce gaz absorb plantele din aer?', 'Dioxid de carbon', 'Oxigen', 'Heliu', 'Azot'],
  ['Știință', 2, 'La ce temperatură îngheață apa, în grade Celsius?', '0', '10', '-10', '32'],
  ['Știință', 2, 'Ce organ pompează sângele prin corp?', 'Inima', 'Ficatul', 'Plămânii', 'Rinichiul'],
  ['Știință', 2, 'Care este simbolul chimic al aurului?', 'Au', 'Ag', 'Gd', 'Go'],
  ['Știință', 3, 'Care este cel mai dur material natural?', 'Diamantul', 'Cuarțul', 'Fierul', 'Granitul'],
  ['Știință', 3, 'Care este cel mai abundent gaz din atmosfera Pământului?', 'Azotul', 'Oxigenul', 'Argonul', 'Dioxidul de carbon'],
  ['Știință', 3, 'Câte oase are corpul unui om adult?', '206', '186', '226', '306'],
  ['Știință', 4, 'Care este simbolul chimic al sodiului?', 'Na', 'So', 'Sd', 'S'],
  ['Știință', 4, 'Ce parte a celulei conține ADN-ul?', 'Nucleul', 'Ribozomul', 'Membrana', 'Vacuola'],
  ['Știință', 4, 'Ce celule ale sângelui luptă împotriva infecțiilor?', 'Globulele albe', 'Globulele roșii', 'Trombocitele', 'Doar plasmocitele'],
  ['Știință', 5, 'Care este numărul atomic al carbonului?', '6', '12', '8', '4'],
  ['Știință', 5, 'Care este unitatea de măsură SI pentru rezistența electrică?', 'Ohmul', 'Voltul', 'Amperul', 'Wattul'],
  ['Știință', 5, 'Care este, aproximativ, viteza luminii în km/s?', '300.000', '150.000', '1.000.000', '30.000'],
  ['Știință', 6, 'Ce element chimic are simbolul K?', 'Potasiu', 'Kripton', 'Calciu', 'Carbon'],
  ['Știință', 6, 'Care este pH-ul apei pure la 25 °C?', '7', '0', '14', '5'],
  ['Știință', 6, 'Ce vitamină produce pielea sub acțiunea soarelui?', 'Vitamina D', 'Vitamina C', 'Vitamina A', 'Vitamina K'],
  ['Știință', 7, 'Care este cel mai abundent element din Univers?', 'Hidrogenul', 'Heliul', 'Oxigenul', 'Carbonul'],
  ['Știință', 7, 'Ce particulă nu are sarcină electrică?', 'Neutronul', 'Protonul', 'Electronul', 'Pozitronul'],
  ['Știință', 7, 'Cine a formulat cele trei legi ale mișcării?', 'Isaac Newton', 'Galileo Galilei', 'Albert Einstein', 'Johannes Kepler'],
  ['Știință', 8, 'Care este unitatea de măsură a frecvenței?', 'Hertzul', 'Joule-ul', 'Pascalul', 'Tesla'],
  ['Știință', 8, 'Cât este, aproximativ, numărul lui Avogadro?', '6,02 × 10^23', '3,14 × 10^8', '9,81 × 10^3', '1,60 × 10^-19'],
  ['Știință', 9, 'Ce om de știință a descoperit penicilina?', 'Alexander Fleming', 'Louis Pasteur', 'Marie Curie', 'Robert Koch'],
  ['Știință', 9, 'Care este simbolul chimic al fierului?', 'Fe', 'Ir', 'In', 'Fr'],
  ['Știință', 10, 'Care este, aproximativ, timpul de înjumătățire al carbonului-14?', '5.730 de ani', '1.200 de ani', '24.000 de ani', '50 de ani'],
  ['Știință', 10, 'Ce enzimă desface dublul helix al ADN-ului în timpul replicării?', 'Helicaza', 'Ligaza', 'Amilaza', 'Lipaza'],
  // ---- Tehnologie ----
  ['Tehnologie', 1, 'Ce înseamnă „www”?', 'World Wide Web', 'Wide Web World', 'Web World Wide', 'World Web Wire'],
  ['Tehnologie', 1, 'Ce tastă șterge textul din stânga cursorului?', 'Backspace', 'Shift', 'Tab', 'Escape'],
  ['Tehnologie', 2, 'Ce înseamnă CPU?', 'Central Processing Unit', 'Computer Power Unit', 'Core Program Utility', 'Central Program Unit'],
  ['Tehnologie', 2, 'Câți biți are un byte?', '8', '4', '16', '10'],
  ['Tehnologie', 3, 'Ce înseamnă RAM?', 'Random Access Memory', 'Read Access Memory', 'Rapid Action Memory', 'Run All Memory'],
  ['Tehnologie', 3, 'Ce sistem de numerație folosește doar cifrele 0 și 1?', 'Binar', 'Zecimal', 'Hexazecimal', 'Octal'],
  ['Tehnologie', 3, 'Ce înseamnă URL?', 'Uniform Resource Locator', 'Universal Route Link', 'Unified Resource Link', 'User Reference Locator'],
  ['Tehnologie', 4, 'Ce înseamnă HTML?', 'HyperText Markup Language', 'High Transfer Machine Language', 'HyperTool Multi Language', 'Home Text Markup Link'],
  ['Tehnologie', 4, 'Câți bytes are 1 kilobyte (definiția binară)?', '1024', '1000', '512', '2048'],
  ['Tehnologie', 4, 'Ce companie a cumpărat și dezvoltă sistemul de operare Android?', 'Google', 'Apple', 'Microsoft', 'Samsung'],
  ['Tehnologie', 5, 'Ce înseamnă GPU?', 'Graphics Processing Unit', 'General Power Unit', 'Graphic Program Utility', 'Global Processing Unit'],
  ['Tehnologie', 5, 'Cât este numărul zecimal 255 în hexazecimal?', 'FF', 'EE', 'F0', '100'],
  ['Tehnologie', 5, 'Ce protocol se folosește pentru trimiterea e-mailurilor?', 'SMTP', 'FTP', 'HTTP', 'SSH'],
  ['Tehnologie', 6, 'Ce înseamnă „AI”?', 'Inteligență artificială', 'Interfață automată', 'Intrare analogică', 'Integrare avansată'],
  ['Tehnologie', 6, 'Care este portul implicit pentru HTTPS?', '443', '80', '21', '8080'],
  ['Tehnologie', 6, 'Ce structură de date funcționează după principiul „ultimul intrat, primul ieșit”?', 'Stiva', 'Coada', 'Arborele', 'Graful'],
  ['Tehnologie', 7, 'Cine este considerată primul programator din istorie?', 'Ada Lovelace', 'Alan Turing', 'Charles Babbage', 'Grace Hopper'],
  ['Tehnologie', 7, 'Ce înseamnă „SQL”?', 'Structured Query Language', 'Simple Question Language', 'System Queue Logic', 'Sequential Query Link'],
  ['Tehnologie', 7, 'Care este complexitatea în timp a căutării binare?', 'O(log n)', 'O(n)', 'O(n^2)', 'O(1)'],
  ['Tehnologie', 8, 'Câți biți are o adresă IPv4?', '32', '64', '128', '16'],
  ['Tehnologie', 8, 'Ce algoritm de sortare are complexitatea medie O(n log n) și folosește un pivot?', 'Quicksort', 'Bubble sort', 'Insertion sort', 'Selection sort'],
  ['Tehnologie', 9, 'Câți biți are o adresă IPv6?', '128', '64', '256', '32'],
  ['Tehnologie', 9, 'Ce test a propus Alan Turing pentru inteligența mașinilor?', 'Jocul imitației', 'Testul opririi', 'Testul Enigma', 'Jocul logicii'],
  ['Tehnologie', 10, 'Cât face 2 la puterea 16?', '65.536', '32.768', '131.072', '16.384'],
  ['Tehnologie', 10, 'Ce poartă logică dă „adevărat” doar când intrările sunt diferite?', 'XOR', 'AND', 'NOR', 'NAND'],
  // ---- Geografie ----
  ['Geografie', 1, 'Care este cel mai mare ocean de pe Pământ?', 'Pacific', 'Atlantic', 'Indian', 'Arctic'],
  ['Geografie', 1, 'Care este capitala Franței?', 'Paris', 'Lyon', 'Marsilia', 'Nisa'],
  ['Geografie', 1, 'Câte continente există?', '7', '5', '6', '8'],
  ['Geografie', 2, 'Care este capitala Italiei?', 'Roma', 'Milano', 'Veneția', 'Napoli'],
  ['Geografie', 2, 'Care este capitala României?', 'București', 'Cluj-Napoca', 'Iași', 'Timișoara'],
  ['Geografie', 2, 'Pe ce continent se află Egiptul?', 'Africa', 'Asia', 'Europa', 'Oceania'],
  ['Geografie', 3, 'Care este cel mai lung fluviu din Europa?', 'Volga', 'Dunărea', 'Rinul', 'Sena'],
  ['Geografie', 3, 'Care este capitala Japoniei?', 'Tokyo', 'Osaka', 'Kyoto', 'Hiroshima'],
  ['Geografie', 3, 'Ce țară are cea mai mare populație?', 'India', 'SUA', 'Rusia', 'Brazilia'],
  ['Geografie', 4, 'Care este capitala Australiei?', 'Canberra', 'Sydney', 'Melbourne', 'Perth'],
  ['Geografie', 4, 'Care este cel mai mare deșert cald?', 'Sahara', 'Gobi', 'Kalahari', 'Atacama'],
  ['Geografie', 4, 'În ce mare se varsă Dunărea?', 'Marea Neagră', 'Marea Adriatică', 'Marea Baltică', 'Marea Egee'],
  ['Geografie', 5, 'Care este capitala Canadei?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
  ['Geografie', 5, 'Care este cel mai înalt munte din lume?', 'Everest', 'K2', 'Kangchenjunga', 'Mont Blanc'],
  ['Geografie', 5, 'Care este cea mai mare țară ca suprafață?', 'Rusia', 'Canada', 'China', 'SUA'],
  ['Geografie', 6, 'Care este capitala Braziliei?', 'Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador'],
  ['Geografie', 6, 'Ce lanț muntos străbate România?', 'Carpații', 'Alpii', 'Pirineii', 'Uralii'],
  ['Geografie', 6, 'Care este cea mai mică țară din lume?', 'Vatican', 'Monaco', 'San Marino', 'Liechtenstein'],
  ['Geografie', 7, 'Care este capitala Turciei?', 'Ankara', 'Istanbul', 'Izmir', 'Antalya'],
  ['Geografie', 7, 'Care este cel mai adânc lac din lume?', 'Lacul Baikal', 'Lacul Superior', 'Lacul Victoria', 'Lacul Tanganyika'],
  ['Geografie', 7, 'Care este cel mai înalt vârf din România?', 'Moldoveanu', 'Negoiu', 'Omu', 'Pietrosul Rodnei'],
  ['Geografie', 8, 'Care este capitala Kazahstanului?', 'Astana', 'Almaty', 'Tașkent', 'Bișkek'],
  ['Geografie', 8, 'Ce strâmtoare desparte Europa de Africa?', 'Strâmtoarea Gibraltar', 'Bosfor', 'Strâmtoarea Ormuz', 'Strâmtoarea Dover'],
  ['Geografie', 9, 'Care este capitala Mongoliei?', 'Ulaanbaatar', 'Astana', 'Bișkek', 'Dușanbe'],
  ['Geografie', 9, 'Ce țară are cele mai multe fusuri orare (inclusiv teritoriile)?', 'Franța', 'Rusia', 'SUA', 'China'],
  ['Geografie', 10, 'Care este capitala Bhutanului?', 'Thimphu', 'Kathmandu', 'Paro', 'Dhaka'],
  ['Geografie', 10, 'Care este cel mai jos punct de pe uscat al Pământului?', 'Țărmul Mării Moarte', 'Valea Morții', 'Lacul Assal', 'Țărmul Mării Caspice'],
  // ---- Istorie ----
  ['Istorie', 1, 'Cine a fost primul om care a pășit pe Lună?', 'Neil Armstrong', 'Buzz Aldrin', 'Iuri Gagarin', 'Michael Collins'],
  ['Istorie', 2, 'În ce țară au fost construite piramidele de la Giza?', 'Egipt', 'Mexic', 'Grecia', 'Irak'],
  ['Istorie', 2, 'Ce vapor s-a scufundat în prima sa călătorie, în 1912?', 'Titanic', 'Lusitania', 'Britannic', 'Olympic'],
  ['Istorie', 3, 'În ce an s-a încheiat Al Doilea Război Mondial?', '1945', '1944', '1939', '1950'],
  ['Istorie', 3, 'Cine a pictat Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Rafael', 'Donatello'],
  ['Istorie', 4, 'În ce an a căzut Zidul Berlinului?', '1989', '1991', '1985', '1979'],
  ['Istorie', 4, 'Cine a fost primul rege al României?', 'Carol I', 'Ferdinand I', 'Mihai I', 'Carol al II-lea'],
  ['Istorie', 4, 'În ce an a ajuns Columb prima dată în America?', '1492', '1498', '1500', '1482'],
  ['Istorie', 5, 'Ce imperiu a construit Colosseumul?', 'Roman', 'Grec', 'Otoman', 'Bizantin'],
  ['Istorie', 5, 'În ce an a avut loc Revoluția Română?', '1989', '1991', '1977', '1968'],
  ['Istorie', 5, 'Cine a fost primul om în spațiu?', 'Iuri Gagarin', 'Neil Armstrong', 'Alan Shepard', 'John Glenn'],
  ['Istorie', 6, 'În ce an a început Primul Război Mondial?', '1914', '1912', '1918', '1905'],
  ['Istorie', 6, 'Ce minune a lumii antice se afla în Alexandria?', 'Farul', 'Colosul', 'Grădinile suspendate', 'Mausoleul'],
  ['Istorie', 6, 'În ce an a avut loc Marea Unire a României?', '1918', '1859', '1877', '1920'],
  ['Istorie', 7, 'Cine a inventat tiparul cu litere mobile în Europa?', 'Johannes Gutenberg', 'William Caxton', 'Aldus Manutius', 'Martin Luther'],
  ['Istorie', 7, 'Ce împărat roman a legalizat creștinismul prin Edictul de la Milano?', 'Constantin cel Mare', 'Nero', 'Augustus', 'Traian'],
  ['Istorie', 7, 'În ce an a avut loc Unirea Principatelor Române (Cuza)?', '1859', '1848', '1877', '1918'],
  ['Istorie', 8, 'Ce civilizație a construit Machu Picchu?', 'Incașii', 'Aztecii', 'Mayașii', 'Olmecii'],
  ['Istorie', 8, 'În ce an a început Revoluția Franceză?', '1789', '1776', '1799', '1815'],
  ['Istorie', 9, 'Ce împărat roman a cucerit Dacia?', 'Traian', 'Hadrian', 'Cezar', 'Augustus'],
  ['Istorie', 9, 'În ce an a căzut Constantinopolul, capitala Bizanțului?', '1453', '1204', '1492', '1389'],
  ['Istorie', 10, 'Ce tratat a încheiat Războiul de Treizeci de Ani?', 'Pacea Westfalică', 'Tratatul de la Utrecht', 'Tratatul de la Versailles', 'Pacea de la Augsburg'],
  ['Istorie', 10, 'Cine a fost ultimul rege al Daciei?', 'Decebal', 'Burebista', 'Dromichete', 'Zalmoxis'],
  // ---- Spațiu ----
  ['Spațiu', 1, 'Ce planetă este numită „Planeta Roșie”?', 'Marte', 'Venus', 'Jupiter', 'Mercur'],
  ['Spațiu', 1, 'Care este cea mai apropiată stea de Pământ?', 'Soarele', 'Proxima Centauri', 'Sirius', 'Steaua Polară'],
  ['Spațiu', 2, 'Care este cea mai mare planetă din Sistemul Solar?', 'Jupiter', 'Saturn', 'Neptun', 'Pământul'],
  ['Spațiu', 2, 'Câte planete are Sistemul Solar?', '8', '9', '7', '10'],
  ['Spațiu', 3, 'Ce planetă este faimoasă pentru inelele sale?', 'Saturn', 'Marte', 'Venus', 'Mercur'],
  ['Spațiu', 3, 'Cum se numește galaxia noastră?', 'Calea Lactee', 'Andromeda', 'Triunghiul', 'Sombrero'],
  ['Spațiu', 4, 'Care este planeta cea mai apropiată de Soare?', 'Mercur', 'Venus', 'Marte', 'Pământul'],
  ['Spațiu', 4, 'Cât timp îi ia, aproximativ, luminii Soarelui să ajungă pe Pământ?', '8 minute', '8 secunde', '8 ore', '1 minut'],
  ['Spațiu', 5, 'Care este cea mai fierbinte planetă din Sistemul Solar?', 'Venus', 'Mercur', 'Marte', 'Jupiter'],
  ['Spațiu', 5, 'Care este cel mai mare satelit al lui Saturn?', 'Titan', 'Europa', 'Ganymede', 'Io'],
  ['Spațiu', 6, 'Care este cel mai mare satelit natural din Sistemul Solar?', 'Ganymede', 'Titan', 'Callisto', 'Luna'],
  ['Spațiu', 6, 'Ce telescop lansat în 2021 observă în infraroșu?', 'James Webb', 'Hubble', 'Kepler', 'Spitzer'],
  ['Spațiu', 7, 'Care este cea mai apropiată galaxie mare de Calea Lactee?', 'Andromeda', 'Triunghiul', 'Vârtejul', 'Marele Nor al lui Magellan'],
  ['Spațiu', 7, 'Ce planetă se rotește „culcată” pe o parte?', 'Uranus', 'Neptun', 'Saturn', 'Venus'],
  ['Spațiu', 8, 'Cum se numește granița din jurul unei găuri negre?', 'Orizontul evenimentelor', 'Sfera fotonilor', 'Singularitatea', 'Inelul de acreție'],
  ['Spațiu', 8, 'Care a fost primul satelit artificial?', 'Sputnik 1', 'Explorer 1', 'Vostok 1', 'Luna 1'],
  ['Spațiu', 9, 'Câți kilometri are, aproximativ, o unitate astronomică?', '150 de milioane', '300 de milioane', '15 milioane', '1 miliard'],
  ['Spațiu', 9, 'Care este cea mai mare planetă pitică din centura de asteroizi?', 'Ceres', 'Pluto', 'Eris', 'Vesta'],
  ['Spațiu', 10, 'Care este cea mai apropiată stea cunoscută de Soare?', 'Proxima Centauri', 'Steaua lui Barnard', 'Sirius A', 'Wolf 359'],
  ['Spațiu', 10, 'Ce măsoară un an-lumină?', 'Distanța', 'Timpul', 'Luminozitatea', 'Viteza'],
  // ---- Natură ----
  ['Natură', 1, 'Care este cel mai mare mamifer?', 'Balena albastră', 'Elefantul', 'Girafa', 'Orca'],
  ['Natură', 1, 'Ce produc albinele?', 'Miere', 'Lapte', 'Mătase', 'Doar ceară'],
  ['Natură', 2, 'Ce animal este numit „regele animalelor”?', 'Leul', 'Tigrul', 'Elefantul', 'Gorila'],
  ['Natură', 2, 'Care este cel mai rapid animal de uscat?', 'Ghepardul', 'Leul', 'Calul', 'Ogarul'],
  ['Natură', 3, 'Câte inimi are o caracatiță?', '3', '1', '2', '8'],
  ['Natură', 3, 'Cum se numește puiul calului?', 'Mânz', 'Ied', 'Miel', 'Vițel'],
  ['Natură', 4, 'Care este cea mai mare pasăre?', 'Struțul', 'Emu', 'Albatrosul', 'Condorul'],
  ['Natură', 4, 'Ce mănâncă în principal urșii panda?', 'Bambus', 'Pește', 'Fructe de pădure', 'Insecte'],
  ['Natură', 5, 'Care dintre aceste animale trăiește cel mai mult?', 'Rechinul de Groenlanda', 'Elefantul', 'Papagalul', 'Țestoasa'],
  ['Natură', 5, 'Care este cel mai înalt animal?', 'Girafa', 'Elefantul', 'Elanul', 'Cămila'],
  ['Natură', 6, 'Cum se numește procesul prin care plantele își fac hrana folosind lumina?', 'Fotosinteză', 'Respirație', 'Fermentație', 'Transpirație'],
  ['Natură', 6, 'Care este cea mai mare reptilă în viață?', 'Crocodilul de apă sărată', 'Dragonul de Komodo', 'Anaconda', 'Țestoasa-lăută'],
  ['Natură', 7, 'Câte compartimente are stomacul unei vaci?', '4', '2', '3', '6'],
  ['Natură', 7, 'Ce specie de copac poate trăi cel mai mult?', 'Pinul Bristlecone', 'Stejarul', 'Baobabul', 'Mesteacănul'],
  ['Natură', 8, 'Ce mamifer poate zbura cu adevărat?', 'Liliacul', 'Veverița zburătoare', 'Petaurul', 'Colugo'],
  ['Natură', 9, 'Care este singurul continent fără furnici native?', 'Antarctica', 'Australia', 'Europa', 'America de Sud'],
  ['Natură', 10, 'Care dintre acestea este cel mai mare organism viu după suprafață?', 'O colonie de ghebe (Armillaria)', 'O balenă albastră', 'Un arbore sequoia', 'Un recif de corali'],
  // ---- Matematică ----
  ['Matematică', 1, 'Câte laturi are un triunghi?', '3', '4', '5', '6'],
  ['Matematică', 2, 'Câte grade are un unghi drept?', '90', '180', '45', '360'],
  ['Matematică', 2, 'Câte laturi are un hexagon?', '6', '5', '7', '8'],
  ['Matematică', 3, 'Câte grade are un cerc complet?', '360', '180', '270', '400'],
  ['Matematică', 3, 'Cât este radical din 144?', '12', '14', '11', '16'],
  ['Matematică', 4, 'Cât este Pi cu două zecimale?', '3,14', '3,41', '3,12', '3,16'],
  ['Matematică', 4, 'Cât este suma unghiurilor unui triunghi?', '180 de grade', '360 de grade', '90 de grade', '270 de grade'],
  ['Matematică', 5, 'Care este cel mai mic număr prim?', '2', '1', '3', '0'],
  ['Matematică', 5, 'Cât reprezintă 15% din 200?', '30', '15', '25', '35'],
  ['Matematică', 6, 'Cum se numește un poligon cu 8 laturi?', 'Octogon', 'Hexagon', 'Heptagon', 'Decagon'],
  ['Matematică', 6, 'Cât face 7 factorial (7!)?', '5040', '720', '40320', '2520'],
  ['Matematică', 7, 'Cât este, aproximativ, numărul de aur?', '1,618', '1,414', '2,718', '3,141'],
  ['Matematică', 7, 'Cât este, aproximativ, numărul lui Euler (e)?', '2,718', '1,618', '3,141', '1,414'],
  ['Matematică', 8, 'Câte numere prime sunt mai mici decât 20?', '8', '7', '9', '10'],
  ['Matematică', 8, 'Cât este, aproximativ, radical din 2?', '1,414', '1,732', '1,618', '1,212'],
  ['Matematică', 9, 'Care este următorul număr din șirul lui Fibonacci: 13, 21, 34, ...?', '55', '48', '68', '51'],
  ['Matematică', 9, 'Câte muchii are un cub?', '12', '8', '6', '24'],
  ['Matematică', 10, 'Cât este suma unghiurilor interioare ale unui hexagon?', '720 de grade', '540 de grade', '900 de grade', '1080 de grade'],
  ['Matematică', 10, 'Cât este logaritm în baza 2 din 1024?', '10', '8', '12', '9'],
  // ---- Cultură ----
  ['Cultură', 1, 'Câte zile are un an bisect?', '366', '365', '364', '367'],
  ['Cultură', 1, 'Câte minute are o oră?', '60', '100', '30', '90'],
  ['Cultură', 2, 'Ce instrument are 88 de clape?', 'Pianul', 'Chitara', 'Vioara', 'Flautul'],
  ['Cultură', 2, 'Câți jucători are pe teren o echipă de fotbal?', '11', '10', '9', '12'],
  ['Cultură', 3, 'În ce loc își au originea Jocurile Olimpice antice?', 'Olimpia', 'Atena', 'Sparta', 'Roma'],
  ['Cultură', 3, 'Cine a scris „Romeo și Julieta”?', 'William Shakespeare', 'Charles Dickens', 'Mark Twain', 'Jane Austen'],
  ['Cultură', 4, 'Cine a compus „Anotimpurile”?', 'Antonio Vivaldi', 'Johann Sebastian Bach', 'Wolfgang Amadeus Mozart', 'Ludwig van Beethoven'],
  ['Cultură', 4, 'Ce poet român a scris „Luceafărul”?', 'Mihai Eminescu', 'Ion Creangă', 'George Coșbuc', 'Tudor Arghezi'],
  ['Cultură', 5, 'Ce sculptor român a creat „Coloana fără sfârșit”?', 'Constantin Brâncuși', 'Ion Jalea', 'Dimitrie Paciurea', 'Nicolae Grigorescu'],
  ['Cultură', 5, 'Câte corzi are o chitară standard?', '6', '4', '5', '7'],
  ['Cultură', 6, 'Ce gimnastă română a obținut primul 10 perfect la Jocurile Olimpice?', 'Nadia Comăneci', 'Simona Amânar', 'Andreea Răducan', 'Lavinia Miloșovici'],
  ['Cultură', 6, 'Cine a scris „Don Quijote”?', 'Miguel de Cervantes', 'Dante Alighieri', 'Homer', 'Victor Hugo'],
  ['Cultură', 7, 'Ce compozitor și-a pierdut auzul, dar a continuat să compună?', 'Ludwig van Beethoven', 'Frédéric Chopin', 'Franz Schubert', 'Joseph Haydn'],
  ['Cultură', 7, 'Ce compozitor român a scris „Rapsodiile române”?', 'George Enescu', 'Ciprian Porumbescu', 'Eugen Doga', 'Ion Ivanovici'],
  ['Cultură', 8, 'Cine a pictat „Noapte înstelată”?', 'Vincent van Gogh', 'Claude Monet', 'Pablo Picasso', 'Salvador Dalí'],
  ['Cultură', 8, 'În ce oraș se află muzeul Luvru?', 'Paris', 'Londra', 'Madrid', 'Viena'],
  ['Cultură', 9, 'Cine a scris romanul „1984”?', 'George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H. G. Wells'],
  ['Cultură', 9, 'Ce inventator născut în România este legat de un avion cu reacție timpuriu (Coandă-1910)?', 'Henri Coandă', 'Aurel Vlaicu', 'Traian Vuia', 'Hermann Oberth'],
  ['Cultură', 10, 'Ce pionier român a zburat la Paris, în 1906, cu un aparat mai greu decât aerul care a decolat prin mijloace proprii?', 'Traian Vuia', 'Aurel Vlaicu', 'Henri Coandă', 'Elie Carafoli'],
  ['Cultură', 10, 'Ce limbă are cei mai mulți vorbitori nativi?', 'Chineza mandarină', 'Engleza', 'Spaniola', 'Hindi'],

  // ================= ROMÂNIA =================
  // ---- Geografie ----
  ['Geografie', 1, 'Ce fluviu formează o mare parte din granița de sud a României?', 'Dunărea', 'Prutul', 'Oltul', 'Mureșul'],
  ['Geografie', 1, 'La ce mare are ieșire România?', 'Marea Neagră', 'Marea Mediterană', 'Marea Adriatică', 'Marea Baltică'],
  ['Geografie', 2, 'Care este cel mai mare port maritim al României?', 'Constanța', 'Galați', 'Brăila', 'Mangalia'],
  ['Geografie', 3, 'În ce județ se află Castelul Bran?', 'Brașov', 'Sibiu', 'Argeș', 'Prahova'],
  ['Geografie', 3, 'Care dintre aceste țări NU se învecinează cu România?', 'Croația', 'Ungaria', 'Serbia', 'Bulgaria'],
  ['Geografie', 4, 'Câte țări se învecinează cu România?', '5', '4', '6', '7'],
  ['Geografie', 4, 'În ce județ se află cea mai mare parte a Deltei Dunării?', 'Tulcea', 'Constanța', 'Galați', 'Brăila'],
  ['Geografie', 4, 'Ce munți traversează șoseaua Transfăgărășan?', 'Munții Făgăraș', 'Munții Bucegi', 'Munții Retezat', 'Munții Rodnei'],
  ['Geografie', 5, 'În ce județ se află Salina Turda?', 'Cluj', 'Alba', 'Mureș', 'Bihor'],
  ['Geografie', 6, 'Care este cel mai mare lac glaciar din România?', 'Lacul Bucura', 'Lacul Bâlea', 'Lacul Sfânta Ana', 'Lacul Roșu'],
  ['Geografie', 6, 'În ce județ se află Lacul Sfânta Ana, format într-un crater vulcanic?', 'Harghita', 'Covasna', 'Neamț', 'Suceava'],
  ['Geografie', 6, 'Care este cel mai înalt vârf din Munții Bucegi?', 'Omu', 'Caraiman', 'Coștila', 'Babele'],
  ['Geografie', 7, 'Care este cel mai estic oraș al României?', 'Sulina', 'Tulcea', 'Mangalia', 'Constanța'],
  // ---- Istorie ----
  ['Istorie', 2, 'Care este Ziua Națională a României?', '1 Decembrie', '24 Ianuarie', '10 Mai', '9 Mai'],
  ['Istorie', 3, 'Ce domnitor al Țării Românești este cunoscut drept Vlad Țepeș?', 'Vlad al III-lea', 'Mircea cel Bătrân', 'Radu cel Frumos', 'Neagoe Basarab'],
  ['Istorie', 4, 'În ce an a aderat România la Uniunea Europeană?', '2007', '2004', '2009', '2001'],
  ['Istorie', 4, 'Ce domnitor al Moldovei a ctitorit Mănăstirea Putna?', 'Ștefan cel Mare', 'Petru Rareș', 'Alexandru cel Bun', 'Dimitrie Cantemir'],
  ['Istorie', 5, 'Care era capitala Daciei înainte de cucerirea romană?', 'Sarmizegetusa Regia', 'Apulum', 'Napoca', 'Porolissum'],
  ['Istorie', 5, 'Ce rege a domnit în timpul Marii Uniri din 1918?', 'Ferdinand I', 'Carol I', 'Carol al II-lea', 'Mihai I'],
  ['Istorie', 6, 'În ce an a realizat Mihai Viteazul prima unire a celor trei țări române?', '1600', '1601', '1595', '1859'],
  ['Istorie', 6, 'În ce an și-a proclamat România independența?', '1877', '1859', '1918', '1881'],
  ['Istorie', 6, 'În ce an a aderat România la NATO?', '2004', '2007', '1999', '2002'],
  ['Istorie', 7, 'Ce regină a României a mers la Conferința de Pace de la Paris (1919) pentru a susține cauza țării?', 'Regina Maria', 'Regina Elisabeta', 'Regina-mamă Elena', 'Regina Ana'],
  ['Istorie', 8, 'Ce domnitor al Țării Românești a condus oastea în bătălia de la Rovine (1395)?', 'Mircea cel Bătrân', 'Mihai Viteazul', 'Ștefan cel Mare', 'Vlad Țepeș'],
  ['Istorie', 8, 'Ce rege dac a unificat triburile geto-dacilor în secolul I î.Hr.?', 'Burebista', 'Decebal', 'Dromichete', 'Zalmoxis'],
  // ---- Cultură ----
  ['Cultură', 1, 'Care este moneda națională a României?', 'Leul', 'Euro', 'Forintul', 'Dinarul'],
  ['Cultură', 2, 'Ce sărbătoare românească se celebrează la 1 martie?', 'Mărțișorul', 'Dragobetele', 'Sânzienele', 'Rusaliile'],
  ['Cultură', 2, 'Cum se numește imnul național al României?', '„Deșteaptă-te, române!”', '„Hora Unirii”', '„Pe-al nostru steag”', '„Trei culori”'],
  ['Cultură', 3, 'Cine a scris „Amintiri din copilărie”?', 'Ion Creangă', 'Mihai Eminescu', 'Ion Luca Caragiale', 'Mihail Sadoveanu'],
  ['Cultură', 4, 'Cine a scris comedia „O scrisoare pierdută”?', 'Ion Luca Caragiale', 'Vasile Alecsandri', 'Ion Creangă', 'Camil Petrescu'],
  ['Cultură', 5, 'Cine a scris romanul „Ion”?', 'Liviu Rebreanu', 'Mihail Sadoveanu', 'George Călinescu', 'Marin Preda'],
  ['Cultură', 5, 'Cine a scris romanul „Baltagul”?', 'Mihail Sadoveanu', 'Liviu Rebreanu', 'Ion Creangă', 'Camil Petrescu'],
  ['Cultură', 5, 'Ce culoare a devenit celebră datorită frescelor Mănăstirii Voroneț?', 'Albastrul', 'Roșul', 'Verdele', 'Galbenul'],
  ['Cultură', 7, 'Cine a pictat „Carul cu boi”?', 'Nicolae Grigorescu', 'Ștefan Luchian', 'Theodor Aman', 'Ion Andreescu'],
  ['Cultură', 7, 'Ce compozitor român a scris celebra „Baladă” pentru vioară?', 'Ciprian Porumbescu', 'George Enescu', 'Gavriil Musicescu', 'Eduard Caudella'],
  ['Cultură', 8, 'Cine a scris versurile imnului „Deșteaptă-te, române!”?', 'Andrei Mureșanu', 'Mihai Eminescu', 'Vasile Alecsandri', 'George Coșbuc'],
  ['Cultură', 8, 'Ce dramaturg născut în România este unul dintre fondatorii teatrului absurdului?', 'Eugen Ionescu', 'Emil Cioran', 'Mircea Eliade', 'Tristan Tzara'],
  ['Cultură', 9, 'Ce mișcare artistică a cofondat Tristan Tzara?', 'Dadaismul', 'Cubismul', 'Suprarealismul', 'Impresionismul'],
  // ---- Sport ----
  ['Cultură', 3, 'Ce jucătoare de tenis din România a câștigat Wimbledon în 2019?', 'Simona Halep', 'Sorana Cîrstea', 'Irina Begu', 'Monica Niculescu'],
  ['Cultură', 3, 'Ce fotbalist român este supranumit „Regele”?', 'Gheorghe Hagi', 'Gheorghe Popescu', 'Adrian Mutu', 'Dan Petrescu'],
  ['Cultură', 5, 'Ce echipă românească a câștigat Cupa Campionilor Europeni în 1986?', 'Steaua București', 'Dinamo București', 'Universitatea Craiova', 'Rapid București'],
  ['Cultură', 6, 'Ce înotător român a devenit campion mondial la 100 m liber în 2022?', 'David Popovici', 'Robert Glință', 'Răzvan Florea', 'Dragoș Coman'],
  ['Cultură', 7, 'În ce an a ajuns România în sferturile de finală ale Campionatului Mondial de fotbal?', '1994', '1990', '1998', '1970'],
  ['Cultură', 7, 'Ce tenismen român a fost primul număr 1 mondial în clasamentul ATP?', 'Ilie Năstase', 'Ion Țiriac', 'Andrei Pavel', 'Victor Hănescu'],
  // ---- Știință și natură ----
  ['Spațiu', 6, 'Cine a fost primul cosmonaut român (1981)?', 'Dumitru Prunariu', 'Aurel Vlaicu', 'Hermann Oberth', 'Henri Coandă'],
  ['Spațiu', 9, 'În ce oraș din România s-a născut pionierul rachetelor Hermann Oberth?', 'Sibiu', 'Brașov', 'Sighișoara', 'Timișoara'],
  ['Știință', 8, 'Ce inventator român a brevetat, în 1827, stiloul cu rezervor?', 'Petrache Poenaru', 'Henri Coandă', 'Ana Aslan', 'Nicolae Paulescu'],
  ['Știință', 8, 'Ce om de știință român a descoperit „pancreina”, legată de descoperirea insulinei?', 'Nicolae Paulescu', 'Victor Babeș', 'Ana Aslan', 'George Emil Palade'],
  ['Știință', 9, 'Ce savant de origine română a primit Premiul Nobel pentru Medicină în 1974?', 'George Emil Palade', 'Nicolae Paulescu', 'Victor Babeș', 'Ioan Cantacuzino'],
  ['Natură', 3, 'Ce animal mare din Carpați are în România una dintre cele mai mari populații din Europa?', 'Ursul brun', 'Bizonul', 'Elanul', 'Ursul polar'],
  ['Natură', 3, 'Ce pasăre este considerată simbolul Deltei Dunării?', 'Pelicanul', 'Barza', 'Vulturul', 'Lebăda'],
  ['Natură', 6, 'Ce floare protejată din Carpați mai este numită „floarea reginei”?', 'Floarea-de-colț', 'Bujorul de munte', 'Ghiocelul', 'Laleaua'],
];

const TRIVIA = TRIVIA_RAW.map((q, i) => ({ id: i, cat: q[0], diff: q[1], text: q[2], answer: q[3], options: [q[3], q[4], q[5], q[6]] }));

const BOT_PREFIX = ['Neo', 'Zero', 'Byte', 'Hex', 'Null', 'Volt', 'Flux', 'Nano', 'Giga', 'Pixel', 'Cipher', 'Echo', 'Nova', 'Quark', 'Rogue', 'Synth', 'Vector', 'Glitch', 'Onyx', 'Ion', 'Delta', 'Kilo', 'Mecha', 'Proxy', 'Rune', 'Shade', 'Turbo', 'Vapor', 'Wire', 'Xeno',
  'Dac', 'Zmeu', 'Haiduc', 'Strigoi', 'Carpat', 'Vlad', 'Bolid', 'Fulger', 'Cuptor', 'Ciber'];
const BOT_SUFFIX = ['Runner', 'Fox', 'Wolf', 'Ghost', 'Mind', 'Core', 'Blade', 'Spark', 'Node', 'Hawk', 'Drift', 'Pulse', 'Bit', 'Coder', 'Byte', 'Viper', 'Storm', 'Knight', 'Moth', 'Lynx', 'Raven', 'Tide', 'Jack', 'Zed', 'Ace',
  'Lup', 'Vultur', 'Șoim', 'Viteazu', 'Hackeru', 'Turbat', 'Furtună', 'Bătăuș'];
const GUILD_NAMES = [
  ['Neon Syndicate', 'NEON'], ['Binary Wolves', 'BWLF'], ['Quantum Order', 'QORD'], ['Ghost Protocol', 'GHST'],
  ['Silicon Saints', 'SSNT'], ['Void Walkers', 'VOID'], ['Chrome Dynasty', 'CHRM'], ['Data Pirates', 'DPIR'],
];
