'use strict';
/* ============================================================
   DATA — trivia bank, bot names, guild names
   Trivia format: [category, difficulty 1-10, question, correct, wrong, wrong, wrong]
   ============================================================ */
const TRIVIA_RAW = [
  // ---- Science ----
  ['Science', 1, 'What is the chemical symbol for water?', 'H2O', 'CO2', 'O2', 'HO'],
  ['Science', 1, 'How many legs does an insect have?', '6', '8', '4', '10'],
  ['Science', 1, 'What gas do plants absorb from the air?', 'Carbon dioxide', 'Oxygen', 'Helium', 'Nitrogen'],
  ['Science', 2, 'What is the freezing point of water in Celsius?', '0', '10', '-10', '32'],
  ['Science', 2, 'Which organ pumps blood through the body?', 'Heart', 'Liver', 'Lungs', 'Kidney'],
  ['Science', 2, 'What is the chemical symbol for gold?', 'Au', 'Ag', 'Gd', 'Go'],
  ['Science', 3, 'What is the hardest natural material?', 'Diamond', 'Quartz', 'Iron', 'Granite'],
  ['Science', 3, 'What is the most abundant gas in Earth\'s atmosphere?', 'Nitrogen', 'Oxygen', 'Argon', 'Carbon dioxide'],
  ['Science', 3, 'How many bones are in the adult human body?', '206', '186', '226', '306'],
  ['Science', 4, 'What is the chemical symbol for sodium?', 'Na', 'So', 'Sd', 'S'],
  ['Science', 4, 'What part of the cell contains DNA?', 'Nucleus', 'Ribosome', 'Membrane', 'Vacuole'],
  ['Science', 4, 'Which blood cells fight infection?', 'White blood cells', 'Red blood cells', 'Platelets', 'Plasma cells only'],
  ['Science', 5, 'What is the atomic number of carbon?', '6', '12', '8', '4'],
  ['Science', 5, 'What is the SI unit of electrical resistance?', 'Ohm', 'Volt', 'Ampere', 'Watt'],
  ['Science', 5, 'What is the speed of light, approximately, in km/s?', '300,000', '150,000', '1,000,000', '30,000'],
  ['Science', 6, 'Which element has the symbol K?', 'Potassium', 'Krypton', 'Calcium', 'Carbon'],
  ['Science', 6, 'What is the pH of pure water at 25 C?', '7', '0', '14', '5'],
  ['Science', 6, 'Which vitamin does the skin make from sunlight?', 'Vitamin D', 'Vitamin C', 'Vitamin A', 'Vitamin K'],
  ['Science', 7, 'What is the most abundant element in the universe?', 'Hydrogen', 'Helium', 'Oxygen', 'Carbon'],
  ['Science', 7, 'What particle has no electric charge?', 'Neutron', 'Proton', 'Electron', 'Positron'],
  ['Science', 7, 'Who proposed the three laws of motion?', 'Isaac Newton', 'Galileo Galilei', 'Albert Einstein', 'Johannes Kepler'],
  ['Science', 8, 'What is the unit of frequency?', 'Hertz', 'Joule', 'Pascal', 'Tesla'],
  ['Science', 8, 'What is Avogadro\'s number, approximately?', '6.02 x 10^23', '3.14 x 10^8', '9.81 x 10^3', '1.60 x 10^-19'],
  ['Science', 9, 'Which scientist discovered penicillin?', 'Alexander Fleming', 'Louis Pasteur', 'Marie Curie', 'Robert Koch'],
  ['Science', 9, 'What is the chemical symbol for iron?', 'Fe', 'Ir', 'In', 'Fr'],
  ['Science', 10, 'What is the half-life of carbon-14, approximately?', '5,730 years', '1,200 years', '24,000 years', '50 years'],
  ['Science', 10, 'Which enzyme unwinds the DNA double helix during replication?', 'Helicase', 'Ligase', 'Amylase', 'Lipase'],
  // ---- Technology ----
  ['Tech', 1, 'What does "www" stand for?', 'World Wide Web', 'Wide Web World', 'Web World Wide', 'World Web Wire'],
  ['Tech', 1, 'Which key is used to delete text to the left of the cursor?', 'Backspace', 'Shift', 'Tab', 'Escape'],
  ['Tech', 2, 'What does CPU stand for?', 'Central Processing Unit', 'Computer Power Unit', 'Core Program Utility', 'Central Program Unit'],
  ['Tech', 2, 'How many bits are in a byte?', '8', '4', '16', '10'],
  ['Tech', 3, 'What does RAM stand for?', 'Random Access Memory', 'Read Access Memory', 'Rapid Action Memory', 'Run All Memory'],
  ['Tech', 3, 'Which number system uses only 0 and 1?', 'Binary', 'Decimal', 'Hexadecimal', 'Octal'],
  ['Tech', 3, 'What does URL stand for?', 'Uniform Resource Locator', 'Universal Route Link', 'Unified Resource Link', 'User Reference Locator'],
  ['Tech', 4, 'What does HTML stand for?', 'HyperText Markup Language', 'High Transfer Machine Language', 'HyperTool Multi Language', 'Home Text Markup Link'],
  ['Tech', 4, 'What is 1 kilobyte in bytes (binary definition)?', '1024', '1000', '512', '2048'],
  ['Tech', 4, 'Which company created the Android operating system (acquired it)?', 'Google', 'Apple', 'Microsoft', 'Samsung'],
  ['Tech', 5, 'What does GPU stand for?', 'Graphics Processing Unit', 'General Power Unit', 'Graphic Program Utility', 'Global Processing Unit'],
  ['Tech', 5, 'What is the hexadecimal value of decimal 255?', 'FF', 'EE', 'F0', '100'],
  ['Tech', 5, 'Which protocol is used to send email?', 'SMTP', 'FTP', 'HTTP', 'SSH'],
  ['Tech', 6, 'What does "AI" stand for?', 'Artificial Intelligence', 'Automated Interface', 'Analog Input', 'Advanced Integration'],
  ['Tech', 6, 'What is the default port for HTTPS?', '443', '80', '21', '8080'],
  ['Tech', 6, 'Which data structure works as Last In, First Out?', 'Stack', 'Queue', 'Tree', 'Graph'],
  ['Tech', 7, 'Who is considered the first computer programmer?', 'Ada Lovelace', 'Alan Turing', 'Charles Babbage', 'Grace Hopper'],
  ['Tech', 7, 'What does "SQL" stand for?', 'Structured Query Language', 'Simple Question Language', 'System Queue Logic', 'Sequential Query Link'],
  ['Tech', 7, 'What is the time complexity of binary search?', 'O(log n)', 'O(n)', 'O(n^2)', 'O(1)'],
  ['Tech', 8, 'How many bits are in an IPv4 address?', '32', '64', '128', '16'],
  ['Tech', 8, 'Which sorting algorithm has average complexity O(n log n) and uses a pivot?', 'Quicksort', 'Bubble sort', 'Insertion sort', 'Selection sort'],
  ['Tech', 9, 'How many bits are in an IPv6 address?', '128', '64', '256', '32'],
  ['Tech', 9, 'What test did Alan Turing propose for machine intelligence?', 'The Imitation Game', 'The Halting Test', 'The Enigma Test', 'The Logic Game'],
  ['Tech', 10, 'What is 2 to the power of 16?', '65,536', '32,768', '131,072', '16,384'],
  ['Tech', 10, 'Which logic gate outputs true only when inputs differ?', 'XOR', 'AND', 'NOR', 'NAND'],
  // ---- Geography ----
  ['Geography', 1, 'What is the largest ocean on Earth?', 'Pacific', 'Atlantic', 'Indian', 'Arctic'],
  ['Geography', 1, 'What is the capital of France?', 'Paris', 'Lyon', 'Marseille', 'Nice'],
  ['Geography', 1, 'How many continents are there?', '7', '5', '6', '8'],
  ['Geography', 2, 'What is the capital of Italy?', 'Rome', 'Milan', 'Venice', 'Naples'],
  ['Geography', 2, 'What is the capital of Romania?', 'Bucharest', 'Cluj-Napoca', 'Iasi', 'Timisoara'],
  ['Geography', 2, 'On which continent is Egypt?', 'Africa', 'Asia', 'Europe', 'Oceania'],
  ['Geography', 3, 'What is the longest river in Europe?', 'Volga', 'Danube', 'Rhine', 'Seine'],
  ['Geography', 3, 'What is the capital of Japan?', 'Tokyo', 'Osaka', 'Kyoto', 'Hiroshima'],
  ['Geography', 3, 'Which country has the largest population?', 'India', 'USA', 'Russia', 'Brazil'],
  ['Geography', 4, 'What is the capital of Australia?', 'Canberra', 'Sydney', 'Melbourne', 'Perth'],
  ['Geography', 4, 'Which desert is the largest hot desert?', 'Sahara', 'Gobi', 'Kalahari', 'Atacama'],
  ['Geography', 4, 'Into which sea does the Danube flow?', 'Black Sea', 'Adriatic Sea', 'Baltic Sea', 'Aegean Sea'],
  ['Geography', 5, 'What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
  ['Geography', 5, 'What is the highest mountain in the world?', 'Mount Everest', 'K2', 'Kangchenjunga', 'Mont Blanc'],
  ['Geography', 5, 'What is the largest country by area?', 'Russia', 'Canada', 'China', 'USA'],
  ['Geography', 6, 'What is the capital of Brazil?', 'Brasilia', 'Rio de Janeiro', 'Sao Paulo', 'Salvador'],
  ['Geography', 6, 'Which mountain range runs through Romania?', 'Carpathians', 'Alps', 'Pyrenees', 'Urals'],
  ['Geography', 6, 'What is the smallest country in the world?', 'Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'],
  ['Geography', 7, 'What is the capital of Turkey?', 'Ankara', 'Istanbul', 'Izmir', 'Antalya'],
  ['Geography', 7, 'Which lake is the deepest in the world?', 'Lake Baikal', 'Lake Superior', 'Lake Victoria', 'Lake Tanganyika'],
  ['Geography', 7, 'What is the highest peak in Romania?', 'Moldoveanu', 'Negoiu', 'Omu', 'Pietrosul Rodnei'],
  ['Geography', 8, 'What is the capital of Kazakhstan?', 'Astana', 'Almaty', 'Tashkent', 'Bishkek'],
  ['Geography', 8, 'Which strait separates Europe and Africa?', 'Strait of Gibraltar', 'Bosphorus', 'Strait of Hormuz', 'Dover Strait'],
  ['Geography', 9, 'What is the capital of Mongolia?', 'Ulaanbaatar', 'Astana', 'Bishkek', 'Dushanbe'],
  ['Geography', 9, 'Which country has the most time zones (including territories)?', 'France', 'Russia', 'USA', 'China'],
  ['Geography', 10, 'What is the capital of Bhutan?', 'Thimphu', 'Kathmandu', 'Paro', 'Dhaka'],
  ['Geography', 10, 'What is the lowest point on land on Earth?', 'Dead Sea shore', 'Death Valley', 'Lake Assal', 'Caspian shore'],
  // ---- History ----
  ['History', 1, 'Who was the first person to walk on the Moon?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins'],
  ['History', 2, 'In which country were the ancient pyramids of Giza built?', 'Egypt', 'Mexico', 'Greece', 'Iraq'],
  ['History', 2, 'Which ship sank on its first voyage in 1912?', 'Titanic', 'Lusitania', 'Britannic', 'Olympic'],
  ['History', 3, 'In which year did World War II end?', '1945', '1944', '1939', '1950'],
  ['History', 3, 'Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Michelangelo', 'Raphael', 'Donatello'],
  ['History', 4, 'In which year did the Berlin Wall fall?', '1989', '1991', '1985', '1979'],
  ['History', 4, 'Who was the first president of the United States?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams'],
  ['History', 4, 'In which year did Columbus first reach the Americas?', '1492', '1498', '1500', '1482'],
  ['History', 5, 'Which empire built the Colosseum?', 'Roman', 'Greek', 'Ottoman', 'Byzantine'],
  ['History', 5, 'In which year did the Romanian Revolution take place?', '1989', '1991', '1977', '1968'],
  ['History', 5, 'Who was the first human in space?', 'Yuri Gagarin', 'Neil Armstrong', 'Alan Shepard', 'John Glenn'],
  ['History', 6, 'In which year did World War I begin?', '1914', '1912', '1918', '1905'],
  ['History', 6, 'Which ancient wonder stood in Alexandria?', 'The Lighthouse', 'The Colossus', 'The Hanging Gardens', 'The Mausoleum'],
  ['History', 6, 'In which year did the Great Union of Romania happen?', '1918', '1859', '1877', '1920'],
  ['History', 7, 'Who invented the movable-type printing press in Europe?', 'Johannes Gutenberg', 'William Caxton', 'Aldus Manutius', 'Martin Luther'],
  ['History', 7, 'Which Roman emperor legalised Christianity with the Edict of Milan?', 'Constantine', 'Nero', 'Augustus', 'Trajan'],
  ['History', 7, 'In which year was the Union of the Romanian Principalities (Cuza)?', '1859', '1848', '1877', '1918'],
  ['History', 8, 'Which civilisation built Machu Picchu?', 'Inca', 'Aztec', 'Maya', 'Olmec'],
  ['History', 8, 'In which year did the French Revolution begin?', '1789', '1776', '1799', '1815'],
  ['History', 9, 'Which Roman emperor conquered Dacia?', 'Trajan', 'Hadrian', 'Caesar', 'Augustus'],
  ['History', 9, 'In which year did the Byzantine capital Constantinople fall?', '1453', '1204', '1492', '1389'],
  ['History', 10, 'Which treaty ended the Thirty Years\' War?', 'Peace of Westphalia', 'Treaty of Utrecht', 'Treaty of Versailles', 'Peace of Augsburg'],
  ['History', 10, 'Who was the last king of Dacia?', 'Decebalus', 'Burebista', 'Dromichaetes', 'Zalmoxis'],
  // ---- Space ----
  ['Space', 1, 'Which planet is known as the Red Planet?', 'Mars', 'Venus', 'Jupiter', 'Mercury'],
  ['Space', 1, 'What is the closest star to Earth?', 'The Sun', 'Proxima Centauri', 'Sirius', 'Polaris'],
  ['Space', 2, 'Which is the largest planet in our solar system?', 'Jupiter', 'Saturn', 'Neptune', 'Earth'],
  ['Space', 2, 'How many planets are in our solar system?', '8', '9', '7', '10'],
  ['Space', 3, 'Which planet is famous for its rings?', 'Saturn', 'Mars', 'Venus', 'Mercury'],
  ['Space', 3, 'What is the name of our galaxy?', 'Milky Way', 'Andromeda', 'Triangulum', 'Sombrero'],
  ['Space', 4, 'Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Mars', 'Earth'],
  ['Space', 4, 'How long does light from the Sun take to reach Earth, roughly?', '8 minutes', '8 seconds', '8 hours', '1 minute'],
  ['Space', 5, 'Which is the hottest planet in our solar system?', 'Venus', 'Mercury', 'Mars', 'Jupiter'],
  ['Space', 5, 'What is the largest moon of Saturn?', 'Titan', 'Europa', 'Ganymede', 'Io'],
  ['Space', 6, 'What is the largest moon in the solar system?', 'Ganymede', 'Titan', 'Callisto', 'The Moon'],
  ['Space', 6, 'Which telescope launched in 2021 observes in infrared?', 'James Webb', 'Hubble', 'Kepler', 'Spitzer'],
  ['Space', 7, 'What is the nearest large galaxy to the Milky Way?', 'Andromeda', 'Triangulum', 'Whirlpool', 'Large Magellanic Cloud'],
  ['Space', 7, 'Which planet rotates on its side?', 'Uranus', 'Neptune', 'Saturn', 'Venus'],
  ['Space', 8, 'What is the name of the boundary around a black hole?', 'Event horizon', 'Photon sphere', 'Singularity', 'Accretion ring'],
  ['Space', 8, 'Which was the first artificial satellite?', 'Sputnik 1', 'Explorer 1', 'Vostok 1', 'Luna 1'],
  ['Space', 9, 'How many kilometres is one astronomical unit, approximately?', '150 million', '300 million', '15 million', '1 billion'],
  ['Space', 9, 'Which dwarf planet is the largest in the asteroid belt?', 'Ceres', 'Pluto', 'Eris', 'Vesta'],
  ['Space', 10, 'What is the closest known star to the Sun?', 'Proxima Centauri', 'Barnard\'s Star', 'Sirius A', 'Wolf 359'],
  ['Space', 10, 'What is a light-year a measure of?', 'Distance', 'Time', 'Brightness', 'Speed'],
  // ---- Nature ----
  ['Nature', 1, 'What is the largest mammal?', 'Blue whale', 'Elephant', 'Giraffe', 'Orca'],
  ['Nature', 1, 'What do bees make?', 'Honey', 'Milk', 'Silk', 'Wax only'],
  ['Nature', 2, 'Which animal is known as the King of the Jungle?', 'Lion', 'Tiger', 'Elephant', 'Gorilla'],
  ['Nature', 2, 'What is the fastest land animal?', 'Cheetah', 'Lion', 'Horse', 'Greyhound'],
  ['Nature', 3, 'How many hearts does an octopus have?', '3', '1', '2', '8'],
  ['Nature', 3, 'What is a baby kangaroo called?', 'Joey', 'Cub', 'Kit', 'Calf'],
  ['Nature', 4, 'Which bird is the largest?', 'Ostrich', 'Emu', 'Albatross', 'Condor'],
  ['Nature', 4, 'What do pandas mainly eat?', 'Bamboo', 'Fish', 'Berries', 'Insects'],
  ['Nature', 5, 'Which animal has the longest lifespan among these?', 'Greenland shark', 'Elephant', 'Parrot', 'Tortoise'],
  ['Nature', 5, 'Which is the tallest animal?', 'Giraffe', 'Elephant', 'Moose', 'Camel'],
  ['Nature', 6, 'What is the process plants use to make food from light?', 'Photosynthesis', 'Respiration', 'Fermentation', 'Transpiration'],
  ['Nature', 6, 'Which is the largest living reptile?', 'Saltwater crocodile', 'Komodo dragon', 'Anaconda', 'Leatherback turtle'],
  ['Nature', 7, 'How many chambers does a cow\'s stomach have?', '4', '2', '3', '6'],
  ['Nature', 7, 'Which tree species can live the longest?', 'Bristlecone pine', 'Oak', 'Baobab', 'Birch'],
  ['Nature', 8, 'Which mammal can truly fly?', 'Bat', 'Flying squirrel', 'Sugar glider', 'Colugo'],
  ['Nature', 9, 'What is the only continent without native ants?', 'Antarctica', 'Australia', 'Europe', 'South America'],
  ['Nature', 10, 'What is the largest living organism by area?', 'A honey fungus colony', 'A blue whale', 'A redwood tree', 'A coral reef'],
  // ---- Math facts ----
  ['Math', 1, 'How many sides does a triangle have?', '3', '4', '5', '6'],
  ['Math', 2, 'How many degrees are in a right angle?', '90', '180', '45', '360'],
  ['Math', 2, 'How many sides does a hexagon have?', '6', '5', '7', '8'],
  ['Math', 3, 'How many degrees are in a full circle?', '360', '180', '270', '400'],
  ['Math', 3, 'What is the square root of 144?', '12', '14', '11', '16'],
  ['Math', 4, 'What is the value of Pi to two decimals?', '3.14', '3.41', '3.12', '3.16'],
  ['Math', 4, 'What is the sum of angles in a triangle?', '180 degrees', '360 degrees', '90 degrees', '270 degrees'],
  ['Math', 5, 'What is the smallest prime number?', '2', '1', '3', '0'],
  ['Math', 5, 'What is 15% of 200?', '30', '15', '25', '35'],
  ['Math', 6, 'What is a polygon with 8 sides called?', 'Octagon', 'Hexagon', 'Heptagon', 'Decagon'],
  ['Math', 6, 'What is 7 factorial (7!)?', '5040', '720', '40320', '2520'],
  ['Math', 7, 'Which number is the golden ratio, approximately?', '1.618', '1.414', '2.718', '3.141'],
  ['Math', 7, 'What is Euler\'s number e, approximately?', '2.718', '1.618', '3.141', '1.414'],
  ['Math', 8, 'How many prime numbers are there below 20?', '8', '7', '9', '10'],
  ['Math', 8, 'What is the square root of 2, approximately?', '1.414', '1.732', '1.618', '1.212'],
  ['Math', 9, 'What is the next number in the Fibonacci sequence: 13, 21, 34, ...?', '55', '48', '68', '51'],
  ['Math', 9, 'How many edges does a cube have?', '12', '8', '6', '24'],
  ['Math', 10, 'What is the sum of interior angles of a hexagon?', '720 degrees', '540 degrees', '900 degrees', '1080 degrees'],
  ['Math', 10, 'What is log base 2 of 1024?', '10', '8', '12', '9'],
  // ---- Culture ----
  ['Culture', 1, 'How many days are in a leap year?', '366', '365', '364', '367'],
  ['Culture', 1, 'How many minutes are in an hour?', '60', '100', '30', '90'],
  ['Culture', 2, 'Which instrument has 88 keys?', 'Piano', 'Guitar', 'Violin', 'Flute'],
  ['Culture', 2, 'How many players are on a football (soccer) team on the field?', '11', '10', '9', '12'],
  ['Culture', 3, 'In which city are the Olympic Games\' origins (ancient)?', 'Olympia', 'Athens', 'Sparta', 'Rome'],
  ['Culture', 3, 'Who wrote "Romeo and Juliet"?', 'William Shakespeare', 'Charles Dickens', 'Mark Twain', 'Jane Austen'],
  ['Culture', 4, 'Who composed the Four Seasons?', 'Antonio Vivaldi', 'Johann Sebastian Bach', 'Wolfgang Amadeus Mozart', 'Ludwig van Beethoven'],
  ['Culture', 4, 'Which Romanian poet wrote "Luceafarul"?', 'Mihai Eminescu', 'Ion Creanga', 'George Cosbuc', 'Tudor Arghezi'],
  ['Culture', 5, 'Which Romanian sculptor created "The Endless Column"?', 'Constantin Brancusi', 'Ion Jalea', 'Dimitrie Paciurea', 'Nicolae Grigorescu'],
  ['Culture', 5, 'How many strings does a standard guitar have?', '6', '4', '5', '7'],
  ['Culture', 6, 'Which Romanian gymnast scored the first perfect 10 at the Olympics?', 'Nadia Comaneci', 'Simona Amanar', 'Andreea Raducan', 'Lavinia Milosovici'],
  ['Culture', 6, 'Who wrote "Don Quixote"?', 'Miguel de Cervantes', 'Dante Alighieri', 'Homer', 'Victor Hugo'],
  ['Culture', 7, 'Which composer became deaf later in life but kept composing?', 'Ludwig van Beethoven', 'Frederic Chopin', 'Franz Schubert', 'Joseph Haydn'],
  ['Culture', 7, 'Which Romanian composer wrote the "Romanian Rhapsodies"?', 'George Enescu', 'Ciprian Porumbescu', 'Eugen Doga', 'Ion Ivanovici'],
  ['Culture', 8, 'Who painted "The Starry Night"?', 'Vincent van Gogh', 'Claude Monet', 'Pablo Picasso', 'Salvador Dali'],
  ['Culture', 8, 'In which city is the Louvre museum?', 'Paris', 'London', 'Madrid', 'Vienna'],
  ['Culture', 9, 'Who wrote the novel "1984"?', 'George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H. G. Wells'],
  ['Culture', 9, 'Which Romanian-born inventor is linked to an early jet aircraft (Coanda-1910)?', 'Henri Coanda', 'Aurel Vlaicu', 'Traian Vuia', 'Hermann Oberth'],
  ['Culture', 10, 'Which Romanian pioneer flew an early self-propelled heavier-than-air machine in Paris in 1906?', 'Traian Vuia', 'Aurel Vlaicu', 'Henri Coanda', 'Elie Carafoli'],
  ['Culture', 10, 'Which language has the most native speakers?', 'Mandarin Chinese', 'English', 'Spanish', 'Hindi'],
];

const TRIVIA = TRIVIA_RAW.map((q, i) => ({ id: i, cat: q[0], diff: q[1], text: q[2], answer: q[3], options: [q[3], q[4], q[5], q[6]] }));

const BOT_PREFIX = ['Neo', 'Zero', 'Byte', 'Hex', 'Null', 'Volt', 'Flux', 'Nano', 'Giga', 'Pixel', 'Cipher', 'Echo', 'Nova', 'Quark', 'Rogue', 'Synth', 'Vector', 'Glitch', 'Onyx', 'Ion', 'Delta', 'Kilo', 'Mecha', 'Proxy', 'Rune', 'Shade', 'Turbo', 'Vapor', 'Wire', 'Xeno'];
const BOT_SUFFIX = ['Runner', 'Fox', 'Wolf', 'Ghost', 'Mind', 'Core', 'Blade', 'Spark', 'Node', 'Hawk', 'Drift', 'Pulse', 'Bit', 'Coder', 'Byte', 'Viper', 'Storm', 'Knight', 'Moth', 'Lynx', 'Raven', 'Tide', 'Jack', 'Zed', 'Ace'];
const GUILD_NAMES = [
  ['Neon Syndicate', 'NEON'], ['Binary Wolves', 'BWLF'], ['Quantum Order', 'QORD'], ['Ghost Protocol', 'GHST'],
  ['Silicon Saints', 'SSNT'], ['Void Walkers', 'VOID'], ['Chrome Dynasty', 'CHRM'], ['Data Pirates', 'DPIR'],
];
