'use strict';
/* ============================================================
   TF DATA — afirmațiile pentru „Adevărat sau Fals”
   Format: [categorie, dificultate 1-3, afirmație, 1 = adevărat / 0 = fals, explicație]
   Pentru afirmațiile false, explicația este varianta adevărată
   (se afișează când jucătorul greșește). Doar fapte sigure,
   fără afirmații care se schimbă în timp.
   ============================================================ */
const TF_RAW = [
  // ================= ROMÂNIA =================
  ['România', 1, 'Capitala României este Bucureștiul.', 1],
  ['România', 1, 'Capitala României este Cluj-Napoca.', 0, 'Capitala României este Bucureștiul.'],
  ['România', 1, 'Dunărea se varsă în Marea Neagră.', 1],
  ['România', 1, 'Dunărea se varsă în Marea Adriatică.', 0, 'Dunărea se varsă în Marea Neagră, prin Delta Dunării.'],
  ['România', 2, 'Vârful Moldoveanu este cel mai înalt vârf din România.', 1],
  ['România', 2, 'Vârful Omu este cel mai înalt vârf din România.', 0, 'Cel mai înalt vârf din România este Moldoveanu (2.544 m), în Munții Făgăraș.'],
  ['România', 2, 'Vârful Moldoveanu se află în Munții Bucegi.', 0, 'Vârful Moldoveanu se află în Munții Făgăraș.'],
  ['România', 2, 'Delta Dunării face parte din patrimoniul mondial UNESCO.', 1],
  ['România', 2, 'Delta Dunării este cea mai mare deltă din Europa.', 0, 'Delta Dunării este a doua ca mărime din Europa, după Delta Volgii.'],
  ['România', 2, 'Cea mai mare parte a Deltei Dunării se află în județul Tulcea.', 1],
  ['România', 2, 'Cea mai mare parte a Deltei Dunării se află în județul Constanța.', 0, 'Cea mai mare parte a Deltei Dunării se află în județul Tulcea.'],
  ['România', 1, 'Marea Unire a avut loc la 1 decembrie 1918.', 1],
  ['România', 2, 'Marea Unire a avut loc în anul 1859.', 0, 'Marea Unire a avut loc în 1918; în 1859 a avut loc Unirea Principatelor.'],
  ['România', 2, 'Marea Unire a fost proclamată la Alba Iulia.', 1],
  ['România', 2, 'Marea Unire a fost proclamată la Iași.', 0, 'Marea Unire a fost proclamată la Alba Iulia, la 1 decembrie 1918.'],
  ['România', 1, 'Ziua Națională a României se sărbătorește pe 1 Decembrie.', 1],
  ['România', 2, 'Unirea Principatelor Române a avut loc în 1859, sub Alexandru Ioan Cuza.', 1],
  ['România', 2, 'Alexandru Ioan Cuza a fost primul domnitor al Principatelor Unite.', 1],
  ['România', 2, 'Alexandru Ioan Cuza a fost primul rege al României.', 0, 'Cuza a fost domnitor; primul rege al României a fost Carol I.'],
  ['România', 1, 'România a aderat la Uniunea Europeană în 2007.', 1],
  ['România', 2, 'România a aderat la Uniunea Europeană în 2004.', 0, 'România a aderat la Uniunea Europeană în 2007; în 2004 a intrat în NATO.'],
  ['România', 2, 'România a devenit membră NATO în 2004.', 1],
  ['România', 2, 'România a devenit membră NATO în 2007.', 0, 'România a devenit membră NATO în 2004; în 2007 a aderat la Uniunea Europeană.'],
  ['România', 1, 'Mihai Eminescu a scris poemul „Luceafărul”.', 1],
  ['România', 1, 'Poemul „Luceafărul” a fost scris de Ion Creangă.', 0, '„Luceafărul” a fost scris de Mihai Eminescu.'],
  ['România', 2, 'Mihai Eminescu s-a născut la Iași.', 0, 'Mihai Eminescu s-a născut în 1850 la Botoșani; copilăria și-a petrecut-o la Ipotești.'],
  ['România', 1, 'Ion Creangă a scris „Amintiri din copilărie”.', 1],
  ['România', 2, 'Constantin Brâncuși a creat „Coloana fără sfârșit” de la Târgu Jiu.', 1],
  ['România', 2, '„Coloana fără sfârșit” a lui Brâncuși se află la Cluj-Napoca.', 0, '„Coloana fără sfârșit” se află la Târgu Jiu.'],
  ['România', 2, 'Sculptura „Gânditorul” este opera lui Constantin Brâncuși.', 0, '„Gânditorul” este opera lui Auguste Rodin; Brâncuși a creat, de exemplu, „Sărutul”.'],
  ['România', 2, 'Nadia Comăneci a obținut primul 10 perfect din istoria gimnasticii olimpice, la Montreal, în 1976.', 1],
  ['România', 2, 'Nadia Comăneci a obținut primul ei 10 perfect la Olimpiada de la Moscova, din 1980.', 0, 'Primul 10 perfect al Nadiei Comăneci a fost la Montreal, în 1976.'],
  ['România', 1, 'Moneda națională a României este leul.', 1],
  ['România', 1, 'Moneda națională a României este euro.', 0, 'Moneda națională a României este leul.'],
  ['România', 1, 'Imnul național al României este „Deșteaptă-te, române!”.', 1],
  ['România', 1, 'Imnul național al României este „Hora Unirii”.', 0, 'Imnul național al României este „Deșteaptă-te, române!”.'],
  ['România', 2, 'Versurile imnului „Deșteaptă-te, române!” au fost scrise de Andrei Mureșanu.', 1],
  ['România', 2, 'Versurile imnului „Deșteaptă-te, române!” au fost scrise de Mihai Eminescu.', 0, 'Versurile imnului au fost scrise de Andrei Mureșanu.'],
  ['România', 1, 'Castelul Peleș se află la Sinaia.', 1],
  ['România', 2, 'Castelul Peleș se află în orașul Brașov.', 0, 'Castelul Peleș se află la Sinaia, în județul Prahova.'],
  ['România', 2, 'Castelul Peleș a fost construit pentru regele Ferdinand I.', 0, 'Castelul Peleș a fost construit pentru regele Carol I.'],
  ['România', 1, 'Castelul Bran se află în județul Brașov.', 1],
  ['România', 2, 'Castelul Bran se află în județul Prahova.', 0, 'Castelul Bran se află în județul Brașov.'],
  ['România', 1, 'Șoseaua Transfăgărășan traversează Munții Făgăraș.', 1],
  ['România', 2, 'Șoseaua Transfăgărășan traversează Munții Bucegi.', 0, 'Transfăgărășanul traversează Munții Făgăraș.'],
  ['România', 2, 'Salina Turda se află în județul Cluj.', 1],
  ['România', 2, 'Salina Turda se află în județul Alba.', 0, 'Salina Turda se află în județul Cluj.'],
  ['România', 2, 'Lacul Sfânta Ana s-a format într-un crater vulcanic.', 1],
  ['România', 2, 'Lacul Sfânta Ana s-a format în urma unei alunecări de teren.', 0, 'Lacul Sfânta Ana s-a format într-un crater vulcanic; Lacul Roșu s-a format în urma unei alunecări de teren.'],
  ['România', 3, 'Lacul Roșu s-a format într-un crater vulcanic.', 0, 'Lacul Roșu s-a format în 1837, când o alunecare de teren a barat valea unui pârâu.'],
  ['România', 2, 'Lacul Sfânta Ana se află în județul Neamț.', 0, 'Lacul Sfânta Ana se află în județul Harghita.'],
  ['România', 2, 'Lacul Roșu se află în apropierea Cheilor Bicazului.', 1],
  ['România', 2, 'Dumitru Prunariu a fost primul cosmonaut român.', 1],
  ['România', 2, 'Dumitru Prunariu a zburat în spațiu în anul 1969.', 0, 'Dumitru Prunariu a zburat în spațiu în 1981.'],
  ['România', 2, 'George Enescu a compus „Rapsodiile române”.', 1],
  ['România', 2, '„Rapsodiile române” au fost compuse de Ciprian Porumbescu.', 0, '„Rapsodiile române” au fost compuse de George Enescu.'],
  ['România', 2, 'Ciprian Porumbescu a compus celebra „Baladă” pentru vioară.', 1],
  ['România', 2, 'Ștefan cel Mare a ctitorit Mănăstirea Putna.', 1],
  ['România', 2, 'Mănăstirea Putna a fost ctitorită de Mihai Viteazul.', 0, 'Mănăstirea Putna a fost ctitorită de Ștefan cel Mare.'],
  ['România', 1, 'Carol I a fost primul rege al României.', 1],
  ['România', 2, 'Primul rege al României a fost Ferdinand I.', 0, 'Primul rege al României a fost Carol I.'],
  ['România', 2, 'Regele Ferdinand I domnea în timpul Marii Uniri din 1918.', 1],
  ['România', 2, 'Regele Carol I domnea în timpul Marii Uniri din 1918.', 0, 'În 1918 domnea regele Ferdinand I; Carol I murise în 1914.'],
  ['România', 2, 'Regina Maria a susținut cauza României la Conferința de Pace de la Paris din 1919.', 1],
  ['România', 2, 'Regina Maria a fost soția regelui Carol I.', 0, 'Regina Maria a fost soția regelui Ferdinand I.'],
  ['România', 1, 'Ion Luca Caragiale a scris comedia „O scrisoare pierdută”.', 1],
  ['România', 2, 'Comedia „O scrisoare pierdută” a fost scrisă de Vasile Alecsandri.', 0, '„O scrisoare pierdută” a fost scrisă de Ion Luca Caragiale.'],
  ['România', 2, 'Liviu Rebreanu a scris romanul „Ion”.', 1],
  ['România', 2, 'Romanul „Ion” a fost scris de Mihail Sadoveanu.', 0, 'Romanul „Ion” a fost scris de Liviu Rebreanu.'],
  ['România', 2, 'Mihail Sadoveanu a scris romanul „Baltagul”.', 1],
  ['România', 1, 'Steaua București a câștigat Cupa Campionilor Europeni în 1986.', 1],
  ['România', 2, 'Steaua București a câștigat Cupa Campionilor Europeni în 1990.', 0, 'Steaua București a câștigat Cupa Campionilor Europeni în 1986.'],
  ['România', 1, 'Simona Halep a câștigat turneul de la Wimbledon în 2019.', 1],
  ['România', 2, 'Simona Halep a câștigat turneul de la Wimbledon în 2015.', 0, 'Simona Halep a câștigat Wimbledonul în 2019.'],
  ['România', 1, 'Gheorghe Hagi este supranumit „Regele”.', 1],
  ['România', 2, 'Ilie Năstase a fost primul număr 1 mondial din clasamentul ATP.', 1],
  ['România', 1, 'Ilie Năstase a fost fotbalist.', 0, 'Ilie Năstase a fost tenismen, primul număr 1 mondial din clasamentul ATP.'],
  ['România', 2, 'Naționala de fotbal a României a ajuns în sferturile de finală ale Campionatului Mondial din 1994.', 1],
  ['România', 2, 'Naționala de fotbal a României a jucat finala Campionatului Mondial din 1994.', 0, 'La Campionatul Mondial din 1994, România a ajuns în sferturile de finală.'],
  ['România', 2, 'David Popovici a devenit campion mondial la 100 m liber în 2022.', 1],
  ['România', 1, 'România se învecinează cu cinci țări.', 1],
  ['România', 1, 'România se învecinează cu Croația.', 0, 'România se învecinează cu Ucraina, Republica Moldova, Bulgaria, Serbia și Ungaria.'],
  ['România', 1, 'România are ieșire la Marea Mediterană.', 0, 'România are ieșire la Marea Neagră.'],
  ['România', 1, 'Mărțișorul se sărbătorește la 1 martie.', 1],
  ['România', 1, 'Mărțișorul se sărbătorește la 1 mai.', 0, 'Mărțișorul se sărbătorește la 1 martie.'],
  ['România', 2, 'Mănăstirea Voroneț este celebră pentru „albastrul de Voroneț”.', 1],
  ['România', 2, 'Bisericile pictate din nordul Moldovei fac parte din patrimoniul mondial UNESCO.', 1],
  ['România', 1, 'Constanța este cel mai mare port maritim al României.', 1],
  ['România', 1, 'Portul Constanța se află pe malul Dunării.', 0, 'Constanța se află pe malul Mării Negre.'],
  ['România', 2, 'Sulina este cel mai estic oraș al României.', 1],
  ['România', 2, 'Sulina este cel mai vestic oraș al României.', 0, 'Sulina este cel mai estic oraș al României.'],
  ['România', 1, 'Drapelul României are culorile albastru, galben și roșu.', 1],
  ['România', 1, 'Drapelul României are culorile roșu, alb și verde.', 0, 'Drapelul României are culorile albastru, galben și roșu.'],
  ['România', 2, 'Benzile de pe drapelul României sunt orizontale.', 0, 'Benzile de pe drapelul României sunt verticale.'],
  ['România', 2, 'Henri Coandă a fost un pionier al aviației, cunoscut pentru efectul care îi poartă numele.', 1],
  ['România', 3, 'Traian Vuia a zburat în 1906, în Franța, cu un aparat mai greu decât aerul care a decolat prin mijloace proprii.', 1],
  ['România', 2, 'Aurel Vlaicu a fost un pionier român al aviației.', 1],
  ['România', 3, 'Petrache Poenaru a brevetat, în 1827, un stilou cu rezervor de cerneală.', 1],
  ['România', 2, 'George Emil Palade a primit Premiul Nobel pentru Medicină.', 1],
  ['România', 2, 'George Emil Palade a primit Premiul Nobel pentru Fizică.', 0, 'George Emil Palade a primit Premiul Nobel pentru Fiziologie sau Medicină, în 1974.'],
  ['România', 2, 'Herta Müller, născută în România, a primit Premiul Nobel pentru Literatură.', 1],
  ['România', 2, 'Herta Müller a primit Premiul Nobel pentru Pace.', 0, 'Herta Müller a primit Premiul Nobel pentru Literatură, în 2009.'],
  ['România', 2, 'Lacul Roșu se află în județul Harghita.', 1],
  ['România', 2, 'Centrul istoric al Sighișoarei face parte din patrimoniul mondial UNESCO.', 1],
  ['România', 2, 'Bisericile de lemn din Maramureș fac parte din patrimoniul mondial UNESCO.', 1],
  ['România', 3, 'Mănăstirea Horezu face parte din patrimoniul mondial UNESCO.', 1],
  ['România', 3, 'Cetățile dacice din Munții Orăștiei fac parte din patrimoniul mondial UNESCO.', 1],
  ['România', 2, 'Cimitirul Vesel se află la Săpânța, în Maramureș.', 1],
  ['România', 2, 'Cimitirul Vesel se află la Sighișoara.', 0, 'Cimitirul Vesel se află la Săpânța, în județul Maramureș.'],
  ['România', 2, 'Orașul Iași a fost capitala Moldovei.', 1],
  ['România', 2, 'Orașul Iași a fost capitala Țării Românești.', 0, 'Iașiul a fost capitala Moldovei.'],
  ['România', 3, 'Suceava a fost cetate de scaun a Moldovei.', 1],
  ['România', 2, 'Burebista a unificat triburile geto-dacilor.', 1],
  ['România', 2, 'Burebista a fost ultimul rege al Daciei.', 0, 'Ultimul rege al Daciei a fost Decebal; Burebista a unificat triburile geto-dacilor.'],
  ['România', 1, 'Împăratul Traian a cucerit Dacia.', 1],
  ['România', 2, 'Dacia a fost cucerită de Iulius Cezar.', 0, 'Dacia a fost cucerită de împăratul Traian, în războaiele din 101–106.'],
  ['România', 2, 'Columna lui Traian se află la Roma.', 1],
  ['România', 2, 'Columna lui Traian se află la Alba Iulia.', 0, 'Columna lui Traian se află la Roma.'],
  ['România', 2, 'Sarmizegetusa Regia a fost capitala Daciei înainte de cucerirea romană.', 1],
  ['România', 3, 'Sarmizegetusa Regia se află în Munții Apuseni.', 0, 'Sarmizegetusa Regia se află în Munții Orăștiei.'],
  ['România', 2, 'Mircea cel Bătrân a condus oastea Țării Românești în bătălia de la Rovine.', 1],
  ['România', 2, 'Ștefan cel Mare a condus oastea în bătălia de la Rovine, din 1395.', 0, 'La Rovine a luptat Mircea cel Bătrân, domnitorul Țării Românești.'],
  ['România', 1, 'Mihai Viteazul a realizat prima unire a celor trei țări române, în 1600.', 1],
  ['România', 2, 'Mihai Viteazul a realizat prima unire a țărilor române în 1859.', 0, 'Mihai Viteazul a realizat prima unire în 1600.'],
  ['România', 2, 'România și-a proclamat independența în 1877.', 1],
  ['România', 2, 'România și-a proclamat independența în 1918.', 0, 'România și-a proclamat independența în 1877.'],
  ['România', 2, 'Nicolae Grigorescu a pictat „Carul cu boi”.', 1],
  ['România', 2, 'Tabloul „Carul cu boi” a fost pictat de Ștefan Luchian.', 0, '„Carul cu boi” a fost pictat de Nicolae Grigorescu.'],
  ['România', 2, 'Nicolae Grigorescu a fost sculptor.', 0, 'Nicolae Grigorescu a fost pictor.'],
  ['România', 2, 'Eugen Ionescu este unul dintre fondatorii teatrului absurdului.', 1],
  ['România', 2, 'Tristan Tzara a fost unul dintre fondatorii dadaismului.', 1],
  ['România', 3, 'Tristan Tzara a fost unul dintre fondatorii cubismului.', 0, 'Tristan Tzara a fost unul dintre fondatorii dadaismului.'],
  ['România', 1, 'Pelicanul este considerat un simbol al Deltei Dunării.', 1],
  ['România', 1, 'În România, pelicanii cuibăresc mai ales în Munții Carpați.', 0, 'În România, pelicanii cuibăresc mai ales în Delta Dunării.'],
  ['România', 1, 'Floarea-de-colț este o plantă ocrotită în România.', 1],
  ['România', 1, 'Ursul brun trăiește în Carpații românești.', 1],
  ['România', 1, 'Munții Carpați formează un arc pe teritoriul României.', 1],
  ['România', 2, 'Râul Olt traversează Carpații Meridionali.', 1],
  ['România', 1, 'Râul Prut formează granița dintre România și Republica Moldova.', 1],
  ['România', 2, 'Râul Prut formează granița dintre România și Bulgaria.', 0, 'Prutul formează granița cu Republica Moldova; granița cu Bulgaria urmează în mare parte Dunărea.'],
  ['România', 1, 'Cluj-Napoca se află în Transilvania.', 1],
  ['România', 2, 'Prin Cluj-Napoca trece râul Someșul Mic.', 1],
  ['România', 2, 'Prin Iași trece râul Someș.', 0, 'Prin Iași trece râul Bahlui.'],
  ['România', 2, 'Muntele Tâmpa se află în Brașov.', 1],
  ['România', 1, 'Biserica Neagră se află în Brașov.', 1],
  ['România', 2, 'Biserica Neagră se află în Sibiu.', 0, 'Biserica Neagră se află în Brașov.'],
  ['România', 1, 'Ateneul Român se află în București.', 1],
  ['România', 1, 'Ateneul Român se află în Iași.', 0, 'Ateneul Român se află în București.'],
  ['România', 1, 'Arcul de Triumf se află în București.', 1],
  ['România', 2, 'Palatul Parlamentului din București este una dintre cele mai mari clădiri administrative din lume.', 1],
  ['România', 2, 'Lacul Bucura este cel mai mare lac glaciar din România.', 1],
  ['România', 3, 'Lacul Bucura se află în Munții Rodnei.', 0, 'Lacul Bucura se află în Munții Retezat.'],
  ['România', 2, 'Peștera Scărișoara adăpostește un ghețar subteran.', 1],
  ['România', 3, 'Peștera Scărișoara se află în Munții Bucegi.', 0, 'Peștera Scărișoara se află în Munții Apuseni.'],
  ['România', 2, 'Barajul Vidraru se află pe râul Argeș.', 1],
  ['România', 2, 'Barajul Vidraru se află pe râul Olt.', 0, 'Barajul Vidraru se află pe râul Argeș.'],
  ['România', 2, 'Hidrocentrala Porțile de Fier se află pe Dunăre.', 1],
  ['România', 2, 'Hidrocentrala Porțile de Fier se află pe Mureș.', 0, 'Hidrocentrala Porțile de Fier se află pe Dunăre.'],
  ['România', 1, 'Vlad Țepeș a fost domnitor al Țării Românești.', 1],
  ['România', 2, 'Vlad Țepeș a fost domnitor al Moldovei.', 0, 'Vlad Țepeș a fost domnitor al Țării Românești.'],
  ['România', 2, 'Dimitrie Cantemir a scris „Descriptio Moldaviae”.', 1],
  ['România', 2, 'Lucrarea „Descriptio Moldaviae” a fost scrisă de Ștefan cel Mare.', 0, '„Descriptio Moldaviae” a fost scrisă de Dimitrie Cantemir.'],
  ['România', 2, 'Tudor Vladimirescu a condus mișcarea revoluționară din 1821.', 1],
  ['România', 2, 'Tudor Vladimirescu a condus revoluția din 1848.', 0, 'Tudor Vladimirescu a condus mișcarea din 1821.'],
  ['România', 1, 'Revoluția Română a avut loc în decembrie 1989.', 1],
  ['România', 2, 'Sibiul a fost Capitală Europeană a Culturii în 2007.', 1],
  ['România', 2, 'Sibiul a fost Capitală Europeană a Culturii în 2021.', 0, 'Sibiul a fost Capitală Europeană a Culturii în 2007.'],
  ['România', 1, 'Micii (mititeii) se prepară din carne tocată.', 1],
  ['România', 1, 'Sarmalele se fac de obicei în foi de varză sau de viță-de-vie.', 1],
  ['România', 2, 'Ion Țiriac a fost jucător de tenis.', 1],
  ['România', 2, 'Gheorghe Zamfir este celebru pentru cântatul la nai.', 1],
  ['România', 2, 'Gheorghe Zamfir este celebru pentru cântatul la vioară.', 0, 'Gheorghe Zamfir este celebru pentru cântatul la nai.'],
  ['România', 3, 'Hermann Oberth, pionier al rachetelor, s-a născut la Sibiu.', 1],
  ['România', 3, 'Hermann Oberth, pionier al rachetelor, s-a născut la Timișoara.', 0, 'Hermann Oberth s-a născut la Sibiu.'],
  ['România', 2, 'Ana Aslan a creat produsul Gerovital.', 1],
  ['România', 2, 'Gerovitalul a fost creat de Nicolae Paulescu.', 0, 'Gerovitalul a fost creat de Ana Aslan.'],
  ['România', 3, 'Nicolae Paulescu a descoperit „pancreina”, legată de descoperirea insulinei.', 1],
  ['România', 2, 'Victor Babeș a fost un bacteriolog român.', 1],
  ['România', 3, 'Emil Racoviță a participat la expediția belgiană în Antarctica, cu nava Belgica.', 1],
  ['România', 3, 'Emil Racoviță a participat la o expediție la Polul Nord, cu nava Belgica.', 0, 'Expediția Belgica, la care a participat Emil Racoviță, a mers în Antarctica.'],
  ['România', 1, 'Mamaia este o stațiune de pe litoralul Mării Negre.', 1],
  ['România', 1, 'Stațiunea Mamaia se află în Munții Apuseni.', 0, 'Mamaia se află pe litoralul Mării Negre, lângă Constanța.'],
  ['România', 1, 'Vama Veche se află pe litoralul românesc.', 1],
  ['România', 2, 'Râul Mureș trece prin Târgu Mureș.', 1],
  ['România', 2, 'Oradea se află în județul Bihor.', 1],
  ['România', 2, 'Oradea se află în județul Arad.', 0, 'Oradea se află în județul Bihor.'],
  ['România', 1, 'Bucureștiul este traversat de râul Dâmbovița.', 1],
  ['România', 1, 'Bucureștiul este traversat de râul Olt.', 0, 'Bucureștiul este traversat de râul Dâmbovița.'],
  ['România', 2, 'Timișoara este reședința județului Arad.', 0, 'Timișoara este reședința județului Timiș; reședința județului Arad este orașul Arad.'],
  ['România', 2, 'Craiova este reședința județului Olt.', 0, 'Craiova este reședința județului Dolj; reședința județului Olt este Slatina.'],
  ['România', 2, 'Cetatea Alba Carolina se află la Sibiu.', 0, 'Cetatea Alba Carolina se află la Alba Iulia.'],
  ['România', 1, '„Miorița” este o baladă populară românească.', 1],
  ['România', 1, 'Hora este un dans popular tradițional românesc.', 1],
  ['România', 2, 'Satele cu biserici fortificate din Transilvania fac parte din patrimoniul UNESCO.', 1],
  ['România', 2, 'Dumitru Prunariu a fost primul om care a pășit pe Lună.', 0, 'Dumitru Prunariu a fost primul cosmonaut român (1981); primul om pe Lună a fost Neil Armstrong.'],
  ['România', 2, 'Ana Aslan a fost primul cosmonaut român.', 0, 'Primul cosmonaut român a fost Dumitru Prunariu; Ana Aslan a fost medic.'],
  ['România', 1, 'Ion Creangă a fost un pictor.', 0, 'Ion Creangă a fost scriitor, autorul „Amintirilor din copilărie”.'],
  ['România', 2, 'Eugen Ionescu a fost unul dintre fondatorii dadaismului.', 0, 'Eugen Ionescu este unul dintre fondatorii teatrului absurdului; dadaismul l-a cofondat Tristan Tzara.'],
  ['România', 2, 'Munții Retezat se află în Carpații Orientali.', 0, 'Munții Retezat se află în Carpații Meridionali.'],
  ['România', 2, 'Munții Făgăraș fac parte din Carpații Meridionali.', 1],
  ['România', 2, 'Munții Rodnei fac parte din Carpații Meridionali.', 0, 'Munții Rodnei fac parte din Carpații Orientali.'],
  ['România', 1, 'Cel mai lung fluviu care trece prin România este Dunărea.', 1],
  ['România', 2, 'Constanța este reședința județului Tulcea.', 0, 'Constanța este reședința județului Constanța; reședința județului Tulcea este orașul Tulcea.'],
  ['România', 2, 'Brăila și Galați sunt porturi la Dunăre.', 1],
  ['România', 1, 'Țara Românească, Moldova și Transilvania au fost numite „țările române”.', 1],
  ['România', 2, 'Ștefan cel Mare a fost domnitor al Țării Românești.', 0, 'Ștefan cel Mare a fost domnitor al Moldovei.'],

  // ================= GEOGRAFIE =================
  ['Geografie', 2, 'Capitala Australiei este Canberra.', 1],
  ['Geografie', 1, 'Capitala Australiei este Sydney.', 0, 'Capitala Australiei este Canberra.'],
  ['Geografie', 2, 'Capitala Canadei este Ottawa.', 1],
  ['Geografie', 2, 'Capitala Canadei este Toronto.', 0, 'Capitala Canadei este Ottawa.'],
  ['Geografie', 1, 'Oceanul Pacific este cel mai mare ocean de pe Pământ.', 1],
  ['Geografie', 1, 'Oceanul Atlantic este cel mai mare ocean de pe Pământ.', 0, 'Cel mai mare ocean este Pacificul.'],
  ['Geografie', 1, 'Everestul este cel mai înalt munte de pe Pământ, măsurat de la nivelul mării.', 1],
  ['Geografie', 2, 'K2 este cel mai înalt munte de pe Pământ.', 0, 'Cel mai înalt munte este Everestul; K2 este al doilea.'],
  ['Geografie', 1, 'Rusia este cea mai mare țară din lume ca suprafață.', 1],
  ['Geografie', 1, 'Monaco este cea mai mică țară din lume.', 0, 'Cea mai mică țară din lume este Vaticanul.'],
  ['Geografie', 1, 'Sahara este cel mai mare deșert cald de pe Pământ.', 1],
  ['Geografie', 2, 'Lacul Baikal este cel mai adânc lac din lume.', 1],
  ['Geografie', 2, 'Volga este cel mai lung fluviu din Europa.', 1],
  ['Geografie', 2, 'Volga se varsă în Marea Neagră.', 0, 'Volga se varsă în Marea Caspică.'],
  ['Geografie', 2, 'Nilul se varsă în Marea Roșie.', 0, 'Nilul se varsă în Marea Mediterană.'],
  ['Geografie', 1, 'Fluviul Amazon curge prin Brazilia.', 1],
  ['Geografie', 1, 'Capitala Japoniei este Tokyo.', 1],
  ['Geografie', 2, 'Capitala Turciei este Istanbul.', 0, 'Capitala Turciei este Ankara.'],
  ['Geografie', 2, 'Capitala Braziliei este Brasília.', 1],
  ['Geografie', 1, 'Capitala Spaniei este Barcelona.', 0, 'Capitala Spaniei este Madrid.'],
  ['Geografie', 2, 'Strâmtoarea Gibraltar desparte Europa de Africa.', 1],
  ['Geografie', 2, 'Strâmtoarea Bosfor desparte Europa de Africa.', 0, 'Bosforul desparte Europa de Asia; Europa e despărțită de Africa de Strâmtoarea Gibraltar.'],
  ['Geografie', 2, 'Orașul Istanbul se întinde pe două continente.', 1],
  ['Geografie', 1, 'Groenlanda este cea mai mare insulă din lume.', 1],
  ['Geografie', 2, 'Ecuatorul trece prin Brazilia.', 1],
  ['Geografie', 2, 'Ecuatorul trece prin Egipt.', 0, 'Ecuatorul nu trece prin Egipt; trece, de exemplu, prin Ecuador, Brazilia și Kenya.'],
  ['Geografie', 1, 'Capitala Ungariei este Budapesta.', 1],
  ['Geografie', 1, 'Capitala Germaniei este München.', 0, 'Capitala Germaniei este Berlinul.'],
  ['Geografie', 1, 'Capitala Bulgariei este Varna.', 0, 'Capitala Bulgariei este Sofia.'],
  ['Geografie', 1, 'Capitala Republicii Moldova este Chișinău.', 1],
  ['Geografie', 1, 'Capitala Ucrainei este Odesa.', 0, 'Capitala Ucrainei este Kievul.'],
  ['Geografie', 1, 'Capitala Serbiei este Belgradul.', 1],
  ['Geografie', 2, 'Muntele Kilimanjaro se află în America de Sud.', 0, 'Muntele Kilimanjaro se află în Africa, în Tanzania.'],
  ['Geografie', 1, 'Munții Anzi se află în America de Sud.', 1],
  ['Geografie', 1, 'Munții Himalaya se află în Africa.', 0, 'Munții Himalaya se află în Asia.'],
  ['Geografie', 2, 'Marea Caspică are legătură directă cu oceanul planetar.', 0, 'Marea Caspică este o întindere de apă închisă, fără legătură naturală cu oceanul.'],
  ['Geografie', 2, 'Madagascar este o insulă din Oceanul Indian.', 1],
  ['Geografie', 1, 'Japonia se află în Oceanul Atlantic.', 0, 'Japonia se află în Oceanul Pacific.'],
  ['Geografie', 2, 'Veneția este construită pe zeci de insule dintr-o lagună.', 1],
  ['Geografie', 1, 'Polul Sud se află în Arctica.', 0, 'Polul Sud se află în Antarctica; Polul Nord se află în Arctica.'],
  ['Geografie', 1, 'Antarctica este cel mai rece continent.', 1],
  ['Geografie', 1, 'Africa este cel mai mare continent ca suprafață.', 0, 'Cel mai mare continent ca suprafață este Asia.'],
  ['Geografie', 1, 'Asia este cel mai mare continent ca suprafață.', 1],
  ['Geografie', 2, 'Canberra este capitala Noii Zeelande.', 0, 'Capitala Noii Zeelande este Wellington; Canberra este capitala Australiei.'],
  ['Geografie', 1, 'Capitala Norvegiei este Oslo.', 1],
  ['Geografie', 1, 'Capitala Suediei este Oslo.', 0, 'Capitala Suediei este Stockholm.'],
  ['Geografie', 1, 'Fluviul Tamisa traversează Londra.', 1],
  ['Geografie', 1, 'Fluviul Sena traversează Roma.', 0, 'Sena traversează Parisul; Roma e traversată de Tibru.'],
  ['Geografie', 2, 'Dunărea trece prin Viena.', 1],
  ['Geografie', 2, 'Dunărea izvorăște din Munții Alpi.', 0, 'Dunărea izvorăște din Pădurea Neagră, în Germania.'],
  ['Geografie', 1, 'Capitala Italiei este Roma.', 1],
  ['Geografie', 1, 'Capitala Franței este Lyon.', 0, 'Capitala Franței este Parisul.'],
  ['Geografie', 1, 'Capitala Greciei este Atena.', 1],
  ['Geografie', 1, 'Capitala Portugaliei este Porto.', 0, 'Capitala Portugaliei este Lisabona.'],
  ['Geografie', 2, 'Capitala Poloniei este Varșovia.', 1],
  ['Geografie', 2, 'Capitala Austriei este Salzburg.', 0, 'Capitala Austriei este Viena.'],
  ['Geografie', 2, 'Capitala Egiptului este Cairo.', 1],
  ['Geografie', 2, 'Capitala Argentinei este Buenos Aires.', 1],
  ['Geografie', 3, 'Capitala Mongoliei este Ulaanbaatar.', 1],
  ['Geografie', 1, 'Islanda este o insulă.', 1],
  ['Geografie', 2, 'Marea Moartă se află în Africa.', 0, 'Marea Moartă se află în Asia, în Orientul Apropiat.'],
  ['Geografie', 2, 'Țărmul Mării Moarte este cel mai jos punct de pe uscat al Pământului.', 1],

  // ================= ISTORIE =================
  ['Istorie', 1, 'Al Doilea Război Mondial s-a încheiat în 1945.', 1],
  ['Istorie', 1, 'Al Doilea Război Mondial a început în 1945.', 0, 'Al Doilea Război Mondial a început în 1939 și s-a încheiat în 1945.'],
  ['Istorie', 1, 'Primul Război Mondial s-a încheiat în 1918.', 1],
  ['Istorie', 2, 'Primul Război Mondial a început în 1918.', 0, 'Primul Război Mondial a început în 1914 și s-a încheiat în 1918.'],
  ['Istorie', 1, 'Zidul Berlinului a căzut în 1989.', 1],
  ['Istorie', 1, 'Cristofor Columb a ajuns prima dată în America în 1592.', 0, 'Columb a ajuns prima dată în America în 1492.'],
  ['Istorie', 2, 'Revoluția Franceză a început în 1789.', 1],
  ['Istorie', 2, 'Constantinopolul a fost cucerit de otomani în 1492.', 0, 'Constantinopolul a fost cucerit de otomani în 1453.'],
  ['Istorie', 2, 'Iulius Cezar a fost asasinat în anul 44 î.Hr.', 1],
  ['Istorie', 1, 'Napoleon Bonaparte a fost împărat al Romei.', 0, 'Napoleon Bonaparte a fost împărat al Franței.'],
  ['Istorie', 2, 'Napoleon a fost învins definitiv la Waterloo, în 1815.', 1],
  ['Istorie', 1, 'Piramidele de la Giza au fost construite de romani.', 0, 'Piramidele de la Giza au fost construite de egiptenii antici.'],
  ['Istorie', 1, 'Neil Armstrong a fost primul om care a pășit pe Lună, în 1969.', 1],
  ['Istorie', 1, 'Iuri Gagarin a fost primul om care a pășit pe Lună.', 0, 'Iuri Gagarin a fost primul om în spațiu (1961); primul om pe Lună a fost Neil Armstrong.'],
  ['Istorie', 1, 'Vaporul Titanic s-a scufundat în 1912.', 1],
  ['Istorie', 1, 'Titanicul s-a scufundat în Oceanul Pacific.', 0, 'Titanicul s-a scufundat în Oceanul Atlantic.'],
  ['Istorie', 2, 'Machu Picchu a fost construit de incași.', 1],
  ['Istorie', 1, 'Colosseumul din Roma a fost construit de greci.', 0, 'Colosseumul a fost construit de romani.'],
  ['Istorie', 2, 'Johannes Gutenberg a introdus în Europa tiparul cu litere mobile.', 1],
  ['Istorie', 2, 'Leonardo da Vinci a pictat tavanul Capelei Sixtine.', 0, 'Tavanul Capelei Sixtine a fost pictat de Michelangelo.'],
  ['Istorie', 1, 'Leonardo da Vinci a pictat „Mona Lisa”.', 1],
  ['Istorie', 2, 'Marele Zid Chinezesc se vede cu ochiul liber de pe Lună.', 0, 'Marele Zid Chinezesc nu se vede cu ochiul liber de pe Lună; este un mit.'],
  ['Istorie', 1, 'Tutankamon a fost faraon al Egiptului.', 1],
  ['Istorie', 1, 'Cleopatra a fost regină a Greciei.', 0, 'Cleopatra a fost regină a Egiptului.'],
  ['Istorie', 3, 'Constantin cel Mare a legalizat creștinismul prin Edictul de la Milano.', 1],
  ['Istorie', 3, 'Pacea Westfalică a încheiat Războiul de Treizeci de Ani.', 1],
  ['Istorie', 3, 'Războiul de o sută de ani a durat exact 100 de ani.', 0, 'Războiul de o sută de ani a durat 116 ani (1337–1453).'],
  ['Istorie', 2, 'Alexandru cel Mare a fost rege al Macedoniei.', 1],
  ['Istorie', 1, 'Vikingii proveneau din Peninsula Iberică.', 0, 'Vikingii proveneau din Scandinavia.'],
  ['Istorie', 3, 'Imperiul Roman de Apus a căzut în anul 476.', 1],
  ['Istorie', 2, 'Declarația de Independență a Statelor Unite a fost adoptată în 1876.', 0, 'Declarația de Independență a SUA a fost adoptată în 1776.'],
  ['Istorie', 3, 'Prima expediție care a ajuns la Polul Sud a fost condusă de Roald Amundsen.', 1],
  ['Istorie', 1, 'Marco Polo a descoperit America.', 0, 'Marco Polo a călătorit în China; Columb a ajuns în America în 1492.'],
  ['Istorie', 2, 'Expediția lui Magellan a realizat prima călătorie în jurul lumii.', 1],
  ['Istorie', 2, 'Iuri Gagarin a fost primul om care a zburat în spațiu.', 1],
  ['Istorie', 2, 'Primul om ajuns în spațiu a fost american.', 0, 'Primul om în spațiu a fost sovieticul Iuri Gagarin, în 1961.'],

  // ================= ȘTIINȚĂ =================
  ['Știință', 1, 'Formula chimică a apei este H2O.', 1],
  ['Știință', 1, 'Simbolul chimic al aurului este Ag.', 0, 'Simbolul aurului este Au; Ag este argintul.'],
  ['Știință', 2, 'Simbolul chimic al fierului este Fe.', 1],
  ['Știință', 1, 'La nivelul mării, apa fierbe la 50 °C.', 0, 'La nivelul mării, apa fierbe la 100 °C.'],
  ['Știință', 1, 'La presiune normală, apa îngheață la 0 °C.', 1],
  ['Știință', 1, 'Lumina se deplasează mai încet decât sunetul.', 0, 'Lumina se deplasează mult mai repede decât sunetul.'],
  ['Știință', 2, 'Viteza luminii în vid este de aproximativ 300.000 km/s.', 1],
  ['Știință', 2, 'Scheletul unui om adult are 306 oase.', 0, 'Scheletul unui om adult are 206 oase.'],
  ['Știință', 1, 'Inima pompează sângele prin corp.', 1],
  ['Știință', 1, 'Plămânii pompează sângele prin corp.', 0, 'Inima pompează sângele; plămânii asigură schimbul de gaze.'],
  ['Știință', 2, 'Diamantul este format din carbon.', 1],
  ['Știință', 2, 'Oxigenul este gazul cel mai abundent din atmosfera Pământului.', 0, 'Cel mai abundent gaz din atmosferă este azotul (aproximativ 78%).'],
  ['Știință', 2, 'Azotul reprezintă aproximativ 78% din atmosfera Pământului.', 1],
  ['Știință', 1, 'Electronii au sarcină electrică pozitivă.', 0, 'Electronii au sarcină electrică negativă.'],
  ['Știință', 2, 'Neutronul nu are sarcină electrică.', 1],
  ['Știință', 2, 'Sunetul se poate propaga prin vid.', 0, 'Sunetul nu se propagă prin vid; are nevoie de un mediu, ca aerul sau apa.'],
  ['Știință', 1, 'Isaac Newton a formulat legea atracției universale.', 1],
  ['Știință', 1, 'Albert Einstein a descoperit penicilina.', 0, 'Penicilina a fost descoperită de Alexander Fleming.'],
  ['Știință', 2, 'Marie Curie a primit de două ori Premiul Nobel.', 1],
  ['Știință', 2, 'Ohmul este unitatea de măsură a tensiunii electrice.', 0, 'Ohmul măsoară rezistența electrică; tensiunea se măsoară în volți.'],
  ['Știință', 2, 'Hertzul este unitatea de măsură a frecvenței.', 1],
  ['Știință', 2, 'Apa pură are pH-ul 0 la 25 °C.', 0, 'Apa pură are pH-ul 7 (neutru) la 25 °C.'],
  ['Știință', 2, 'Pielea produce vitamina D sub acțiunea razelor soarelui.', 1],
  ['Știință', 2, 'ADN-ul se află în principal în nucleul celulei.', 1],
  ['Știință', 1, 'Globulele roșii sunt cele care luptă împotriva infecțiilor.', 0, 'Globulele albe luptă împotriva infecțiilor; cele roșii transportă oxigenul.'],
  ['Știință', 2, 'Hidrogenul este cel mai abundent element din Univers.', 1],
  ['Știință', 1, 'Mercurul (metalul) este lichid la temperatura camerei.', 1],
  ['Știință', 1, 'Un kilogram de fier este mai greu decât un kilogram de pene.', 0, 'Amândouă cântăresc la fel: un kilogram.'],
  ['Știință', 2, 'Un byte are 8 biți.', 1],
  ['Știință', 2, 'Un byte are 10 biți.', 0, 'Un byte are 8 biți.'],
  ['Știință', 1, 'Sistemul binar folosește doar cifrele 0 și 1.', 1],
  ['Știință', 2, 'HTML este un limbaj de interogare a bazelor de date.', 0, 'HTML este un limbaj de marcare pentru pagini web; SQL este limbajul pentru baze de date.'],
  ['Știință', 2, 'Ada Lovelace este considerată primul programator din istorie.', 1],
  ['Știință', 1, 'Lumina albă este formată dintr-o singură culoare.', 0, 'Lumina albă este un amestec de culori, cum se vede într-un curcubeu.'],
  ['Știință', 1, 'Curcubeul apare când lumina se descompune în picăturile de apă.', 1],
  ['Știință', 2, 'Diamantul este cel mai moale mineral.', 0, 'Diamantul este cel mai dur mineral natural; cel mai moale este talcul.'],
  ['Știință', 3, 'Talcul este cel mai moale mineral de pe scara Mohs.', 1],
  ['Știință', 1, 'Plantele produc oxigen prin fotosinteză.', 1],
  ['Știință', 3, 'Carbonul are numărul atomic 6.', 1],
  ['Știință', 2, 'Simbolul chimic al sodiului este So.', 0, 'Simbolul chimic al sodiului este Na.'],

  // ================= SPAȚIU (categoria Știință) =================
  ['Știință', 1, 'Pământul se rotește în jurul axei sale aproximativ o dată pe zi.', 1],
  ['Știință', 1, 'Luna este o planetă.', 0, 'Luna este satelitul natural al Pământului.'],
  ['Știință', 1, 'Planeta Saturn are inele.', 1],
  ['Știință', 1, 'Jupiter este planeta cea mai apropiată de Soare.', 0, 'Planeta cea mai apropiată de Soare este Mercur.'],
  ['Știință', 2, 'Venus este cea mai fierbinte planetă din Sistemul Solar.', 1],
  ['Știință', 1, 'Marte este cea mai mare planetă din Sistemul Solar.', 0, 'Cea mai mare planetă din Sistemul Solar este Jupiter.'],
  ['Știință', 1, 'Sistemul Solar are opt planete.', 1],
  ['Știință', 2, 'Pluto este considerat și astăzi a noua planetă a Sistemului Solar.', 0, 'Din 2006, Pluto este considerat planetă pitică.'],
  ['Știință', 2, 'Lumina Soarelui ajunge pe Pământ în aproximativ 8 minute.', 1],
  ['Știință', 1, 'Soarele se învârte în jurul Pământului.', 0, 'Pământul se învârte în jurul Soarelui.'],
  ['Știință', 1, 'Galaxia noastră se numește Calea Lactee.', 1],
  ['Știință', 2, 'Pământul se află în galaxia Andromeda.', 0, 'Pământul se află în Calea Lactee; Andromeda este o galaxie vecină.'],
  ['Știință', 3, 'Ganymede, satelit al lui Jupiter, este cel mai mare satelit din Sistemul Solar.', 1],
  ['Știință', 2, 'Titan este un satelit al planetei Marte.', 0, 'Titan este cel mai mare satelit al lui Saturn.'],
  ['Știință', 2, 'Sputnik 1 a fost primul satelit artificial al Pământului.', 1],
  ['Știință', 1, 'Un an-lumină este o unitate de distanță.', 1],
  ['Știință', 2, 'Un an-lumină este o unitate de măsură a timpului.', 0, 'Un an-lumină măsoară distanța: cât parcurge lumina într-un an.'],
  ['Știință', 1, 'Marte este numită „Planeta Roșie”.', 1],
  ['Știință', 2, 'Uranus se rotește aproape „culcat” pe o parte.', 1],
  ['Știință', 1, 'Soarele este o stea.', 1],

  // ================= NATURĂ =================
  ['Natură', 1, 'Balena albastră este cel mai mare animal de pe Pământ.', 1],
  ['Natură', 1, 'Elefantul este cel mai mare mamifer de pe Pământ.', 0, 'Cel mai mare mamifer este balena albastră; elefantul african este cel mai mare animal de uscat.'],
  ['Natură', 2, 'Elefantul african este cel mai mare animal de uscat.', 1],
  ['Natură', 1, 'Ghepardul este cel mai rapid animal de uscat.', 1],
  ['Natură', 1, 'Leul este cel mai rapid animal de uscat.', 0, 'Cel mai rapid animal de uscat este ghepardul.'],
  ['Natură', 2, 'Caracatița are trei inimi.', 1],
  ['Natură', 1, 'Păianjenii au șase picioare.', 0, 'Păianjenii au opt picioare; insectele au șase.'],
  ['Natură', 1, 'Insectele au șase picioare.', 1],
  ['Natură', 1, 'Balena este un pește.', 0, 'Balena este un mamifer.'],
  ['Natură', 1, 'Delfinii sunt mamifere.', 1],
  ['Natură', 1, 'Liliecii sunt păsări.', 0, 'Liliecii sunt mamifere, singurele capabile de zbor activ.'],
  ['Natură', 2, 'Liliacul este singurul mamifer capabil de zbor activ.', 1],
  ['Natură', 1, 'Pinguinii trăiesc în mod natural la Polul Nord.', 0, 'Pinguinii trăiesc aproape exclusiv în emisfera sudică.'],
  ['Natură', 1, 'Pinguinii nu pot zbura.', 1],
  ['Natură', 1, 'Struțul poate zbura.', 0, 'Struțul nu poate zbura, dar aleargă foarte repede.'],
  ['Natură', 1, 'Struțul este cea mai mare pasăre.', 1],
  ['Natură', 1, 'Urșii panda uriași se hrănesc mai ales cu pește.', 0, 'Urșii panda uriași se hrănesc mai ales cu bambus.'],
  ['Natură', 1, 'Girafa este cel mai înalt animal.', 1],
  ['Natură', 1, 'Albinele produc mătase.', 0, 'Albinele produc miere; mătasea este produsă de viermii de mătase.'],
  ['Natură', 1, 'Viermii de mătase produc mătase.', 1],
  ['Natură', 2, 'Ciupercile sunt plante.', 0, 'Ciupercile formează un regn separat de plante și de animale.'],
  ['Natură', 1, 'Rechinii sunt mamifere.', 0, 'Rechinii sunt pești.'],
  ['Natură', 2, 'Stomacul vacii are patru compartimente.', 1],
  ['Natură', 2, 'Broaștele sunt reptile.', 0, 'Broaștele sunt amfibieni.'],
  ['Natură', 1, 'Broaștele sunt amfibieni.', 1],
  ['Natură', 3, 'Antarctica are specii de furnici native.', 0, 'Antarctica este singurul continent fără furnici native.'],
  ['Natură', 1, 'Koala trăiește în mod natural în Australia.', 1],
  ['Natură', 1, 'Cangurii trăiesc în mod natural în Africa.', 0, 'Cangurii trăiesc în mod natural în Australia și Noua Guinee.'],
  ['Natură', 1, 'Fluturii ies din ou cu aripi gata formate.', 0, 'Din ou iese o omidă, care devine fluture prin metamorfoză.'],
  ['Natură', 1, 'Mormolocul este larva broaștei.', 1],
  ['Natură', 2, 'Majoritatea bufnițelor sunt active ziua.', 0, 'Majoritatea bufnițelor sunt active noaptea.'],
  ['Natură', 1, 'Lupii trăiesc de obicei în haite.', 1],
  ['Natură', 1, 'Stejarul face ghinde.', 1],
  ['Natură', 1, 'Bradul își pierde frunzele toamna.', 0, 'Bradul este un conifer veșnic verde; laricele este conifer care își pierde acele toamna.'],
  ['Natură', 3, 'Laricele este un conifer care își pierde acele toamna.', 1],
  ['Natură', 1, 'Puiul calului se numește mânz.', 1],
  ['Natură', 1, 'Puiul oii se numește ied.', 0, 'Puiul oii se numește miel; iedul este puiul caprei.'],
  ['Natură', 2, 'Delfinii respiră aer prin plămâni.', 1],

  // ================= SPORT =================
  ['Sport', 1, 'O echipă de fotbal are 11 jucători pe teren.', 1],
  ['Sport', 1, 'O echipă de baschet are 7 jucători pe teren.', 0, 'O echipă de baschet are 5 jucători pe teren.'],
  ['Sport', 2, 'Jocurile Olimpice antice își au originea la Olimpia, în Grecia.', 1],
  ['Sport', 1, 'Jocurile Olimpice de vară au loc, de regulă, la fiecare doi ani.', 0, 'Jocurile Olimpice de vară au loc, de regulă, la fiecare patru ani.'],
  ['Sport', 1, 'Simbolul olimpic are cinci inele.', 1],
  ['Sport', 1, 'Un maraton are 21 de kilometri.', 0, 'Maratonul are 42,195 km; 21,0975 km are semimaratonul.'],
  ['Sport', 2, 'Maratonul are 42,195 km.', 1],
  ['Sport', 2, 'La tenis, un set se câștigă cu trei game-uri.', 0, 'Un set se câștigă, de regulă, la șase game-uri, cu cel puțin două diferență sau prin tie-break.'],
  ['Sport', 1, 'La volei, o echipă are 6 jucători pe teren.', 1],
  ['Sport', 1, 'Rugby se joacă cu o minge rotundă.', 0, 'Rugby se joacă cu o minge ovală.'],
  ['Sport', 1, 'Turul Franței este o competiție de ciclism.', 1],
  ['Sport', 2, 'Turneul de la Wimbledon se joacă pe zgură.', 0, 'Wimbledonul se joacă pe iarbă; Roland Garros se joacă pe zgură.'],
  ['Sport', 2, 'Turneul Roland Garros se joacă pe zgură.', 1],
  ['Sport', 1, 'Un meci de fotbal are, fără prelungiri, 60 de minute.', 0, 'Un meci de fotbal are 90 de minute (două reprize de 45).'],
  ['Sport', 1, 'Tabla de șah are 64 de pătrate.', 1],
  ['Sport', 1, 'La șah, fiecare jucător începe cu 10 pioni.', 0, 'La șah, fiecare jucător începe cu 8 pioni.'],
  ['Sport', 2, 'Primele Jocuri Olimpice moderne au avut loc la Atena, în 1896.', 1],
  ['Sport', 2, 'Primul Campionat Mondial de fotbal a avut loc în 1950.', 0, 'Primul Campionat Mondial de fotbal a avut loc în 1930, în Uruguay.'],
  ['Sport', 2, 'Primul Campionat Mondial de fotbal a fost găzduit de Uruguay.', 1],
  ['Sport', 1, 'La baschet, un coș marcat de dincolo de linia de trei puncte valorează 2 puncte.', 0, 'Un coș de dincolo de linia de trei puncte valorează 3 puncte.'],
  ['Sport', 1, 'Hocheiul pe gheață se joacă cu o minge.', 0, 'Hocheiul pe gheață se joacă cu un puc.'],
  ['Sport', 1, 'Meciurile de box se dispută într-un ring.', 1],
  ['Sport', 1, 'La fotbal, portarul poate prinde mingea cu mâna în propriul careu.', 1],
  ['Sport', 2, 'Un meci de handbal se joacă cu câte 11 jucători pe teren în fiecare echipă.', 0, 'La handbal, fiecare echipă are 7 jucători pe teren (inclusiv portarul).'],

  // ================= CULTURĂ =================
  ['Cultură', 1, 'William Shakespeare a scris „Romeo și Julieta”.', 1],
  ['Cultură', 2, 'Romanul „Don Quijote” a fost scris de Dante Alighieri.', 0, '„Don Quijote” a fost scris de Miguel de Cervantes.'],
  ['Cultură', 2, 'Dante Alighieri a scris „Divina Comedie”.', 1],
  ['Cultură', 2, 'Simfonia a 9-a, cu „Oda bucuriei”, a fost compusă de Vivaldi.', 0, 'Simfonia a 9-a a fost compusă de Ludwig van Beethoven.'],
  ['Cultură', 2, 'Ludwig van Beethoven a compus Simfonia a 9-a.', 1],
  ['Cultură', 1, 'Vincent van Gogh a pictat „Mona Lisa”.', 0, '„Mona Lisa” a fost pictată de Leonardo da Vinci; Van Gogh a pictat „Noapte înstelată”.'],
  ['Cultură', 2, 'Vincent van Gogh a pictat „Noapte înstelată”.', 1],
  ['Cultură', 1, 'Muzeul Luvru se află la Londra.', 0, 'Muzeul Luvru se află la Paris.'],
  ['Cultură', 2, 'Romanul „1984” a fost scris de George Orwell.', 1],
  ['Cultură', 2, '„Micul Prinț” a fost scris de Jules Verne.', 0, '„Micul Prinț” a fost scris de Antoine de Saint-Exupéry.'],
  ['Cultură', 2, 'Jules Verne a scris „Ocolul Pământului în 80 de zile”.', 1],
  ['Cultură', 2, 'Un pian standard are 52 de clape.', 0, 'Un pian standard are 88 de clape.'],
  ['Cultură', 1, 'Chitara clasică are, de obicei, șase corzi.', 1],
  ['Cultură', 1, 'Vioara are șase corzi.', 0, 'Vioara are patru corzi.'],
  ['Cultură', 2, '„Iliada” este atribuită lui Homer.', 1],
  ['Cultură', 2, 'Pablo Picasso a fost un pictor italian.', 0, 'Pablo Picasso a fost un pictor spaniol.'],
  ['Cultură', 3, 'Pablo Picasso a fost unul dintre fondatorii cubismului.', 1],
  ['Cultură', 2, 'Wolfgang Amadeus Mozart a trăit în secolul al XX-lea.', 0, 'Mozart a trăit în secolul al XVIII-lea (1756–1791).'],
  ['Cultură', 1, 'Statuia Libertății se află la New York.', 1],
  ['Cultură', 1, 'Turnul Eiffel se află la Roma.', 0, 'Turnul Eiffel se află la Paris.'],
  ['Cultură', 1, 'Turnul înclinat se află la Pisa.', 1],
  ['Cultură', 1, 'Turnul cu ceasul Big Ben se află la Paris.', 0, 'Big Ben se află la Londra.'],
  ['Cultură', 1, 'Opera din Sydney se află în Australia.', 1],
  ['Cultură', 1, 'Taj Mahal se află în Egipt.', 0, 'Taj Mahal se află în India.'],
  ['Cultură', 1, 'Colosseumul se află la Roma.', 1],
  ['Cultură', 1, 'Seria „Harry Potter” a fost scrisă de J.R.R. Tolkien.', 0, '„Harry Potter” a fost scrisă de J.K. Rowling; Tolkien a scris „Stăpânul inelelor”.'],
  ['Cultură', 2, 'J.R.R. Tolkien a scris „Stăpânul inelelor”.', 1],
  ['Cultură', 1, 'Un an bisect are 365 de zile.', 0, 'Un an bisect are 366 de zile.'],
  ['Cultură', 1, 'Un an bisect are 366 de zile.', 1],
  ['Cultură', 1, 'Un secol are 100 de ani.', 1],
  ['Cultură', 1, 'Un mileniu are 100 de ani.', 0, 'Un mileniu are 1.000 de ani; un secol are 100.'],
  ['Cultură', 2, 'Antonio Vivaldi a compus „Anotimpurile”.', 1],
  ['Cultură', 2, 'Charles Dickens a scris „Romeo și Julieta”.', 0, '„Romeo și Julieta” a fost scrisă de William Shakespeare.'],
  ['Cultură', 2, 'Michelangelo a sculptat statuia lui David din Florența.', 1],
];
